confluentinc/kafka-rest

bin/kafka-rest-start
bin/kafka-rest-stop
bin/kafka-rest-stop-service
docs/intro.rst
pom.xml
src/main/java/io/confluent/kafkarest/KafkaRestMain.java
src/main/java/io/confluent/kafkarest/Main.java

@ewencp 
Very similar to https://github.com/confluentinc/schema-registry/pull/203

Issue 94 rename main

---

docs/api.rst

Clarify partitioning behavior for produce requests

---

src/main/java/io/confluent/kafkarest/MetadataObserver.java

#105: Fix for Race condition when consuming while topic is being created

KAFKA-REST:105 Fix for Race condition when consuming while topic is being created

---

docs/changelog.rst
docs/intro.rst
pom.xml

This is my merge of the 2.x branch into master. I'm creating a new PR because there were conflicts. They were trivial, yet considering I haven't contributed here much, I created the PR to be safe. I think I'm doing this right, but let me know if not.

2.x merge to master

---

docs/intro.rst

fix typo in intro.

---

docs/config.rst
docs/index.rst
docs/security.rst
src/main/java/io/confluent/kafkarest/KafkaRestConfig.java

I need help with one issue: the security doc I introduce doesn't show up in the top-level menu when I `make html`. Maybe this is a local configuration issue?
Depends on: https://github.com/confluentinc/rest-utils/pull/38
Don't merge until https://github.com/confluentinc/rest-utils/pull/38 is merged.

https support.

---

docs/config.rst

added description of JVM parameters for SASL configuration

---

docs/intro.rst

Added topic name to return payload

Documentation fixes

---

src/main/java/io/confluent/kafkarest/entities/TopicPartitionOffsetMetadata.java

Need to use `String::equals()`
Found using IntelliJ

Strings cannot be compared using !=

---

src/main/java/io/confluent/kafkarest/resources/v2/ConsumersResource.java

Not null validation is not required for commit request because null request should commit all records

Null validation for consumer POST requests

---

.gitignore
docs/monitoring.rst

Adds supplemental navigation and table headers.

DOCS-10 - Improve findability of operational metrics

---

docs/intro.rst

https://confluentinc.atlassian.net/browse/DOCS-323

DOCS-323 - Remove old version quick start

---

docs/index.rst

DOCS-647 - Add GH repo info to docs

---

docs/api.rst
docs/config.rst
docs/deployment.rst
docs/intro.rst

https://confluentinc.atlassian.net/browse/DOCS-652

DOCS-652 - Fix SR terminology

---

docs/api.rst
docs/config.rst
docs/index.rst
docs/monitoring.rst

https://confluentinc.atlassian.net/browse/DOCS-851

DOCS-851 - Remove in-page navigation

---

kafka-rest/src/main/java/io/confluent/kafkarest/ConsumerManager.java
kafka-rest/src/main/java/io/confluent/kafkarest/ConsumerState.java
kafka-rest/src/main/java/io/confluent/kafkarest/v2/KafkaConsumerManager.java
kafka-rest/src/main/java/io/confluent/kafkarest/v2/KafkaConsumerState.java
kafka-rest/src/test/java/io/confluent/kafkarest/integration/ConsumerTimeoutTest.java

Merge 4.0.x to 4.1.x

---

docs/deployment.rst

This doc changes adds a section on high availability considerations for REST Proxy clients. It also makes some other minor changes to the deployment page.

DOCS-1187 REST Proxy HA

---

testing/environments/minimal/README.md
testing/environments/minimal/docker-compose.yml
testing/environments/minimal/run.sh
testing/image/Dockerfile
testing/image/bin/entrypoint.sh
testing/image/config/log4j.properties

This test environment builds a development image from source, then spins up a Kafka cluster with three brokers and the rest-proxy.

Adds a testing environment for kafka-rest.

---

kafka-rest/src/test/java/io/confluent/kafkarest/unit/ProtobufConverterTest.java
kafka-rest/src/test/java/io/confluent/kafkarest/v2/LoadTest.java

Generated maps are now properly nested.

Fixes for map handling in Protobuf plugin

---

kafka-rest/src/main/java/io/confluent/kafkarest/controllers/BrokerManager.java
kafka-rest/src/main/java/io/confluent/kafkarest/controllers/BrokerManagerImpl.java
kafka-rest/src/main/java/io/confluent/kafkarest/controllers/ClusterManagerImpl.java
kafka-rest/src/main/java/io/confluent/kafkarest/controllers/Entities.java
kafka-rest/src/main/java/io/confluent/kafkarest/controllers/KafkaFutures.java
kafka-rest/src/main/java/io/confluent/kafkarest/entities/Broker.java
kafka-rest/src/main/java/io/confluent/kafkarest/entities/Cluster.java
kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/BrokerData.java
kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/GetBrokerResponse.java
kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/ListBrokersResponse.java
kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/AsyncResponses.java
kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/BrokersResource.java
kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/ClustersResource.java
kafka-rest/src/test/java/io/confluent/kafkarest/controllers/BrokerManagerImplTest.java
kafka-rest/src/test/java/io/confluent/kafkarest/controllers/ClusterManagerImplTest.java
kafka-rest/src/test/java/io/confluent/kafkarest/integration/ClusterTestHarness.java
kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/BrokersResourceIntegrationTest.java
kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/BrokersResourceTest.java
kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/ClustersResourceTest.java
kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/CompletableFutures.java

This PR adds endpoints to list and get brokers:
* /v3/clusters/{clusterId}/brokers
* /v3/clusters/{clusterId}/brokers/{brokerId}

CLIENTS-1475: Add LIST/GET Brokers V3 endpoints.

---

checkstyle/suppressions.xml
kafka-rest/src/main/java/io/confluent/kafkarest/controllers/TopicManager.java
kafka-rest/src/main/java/io/confluent/kafkarest/controllers/TopicManagerImpl.java
kafka-rest/src/main/java/io/confluent/kafkarest/entities/Topic.java
kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/CreateTopicRequest.java
kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/CreateTopicResponse.java
kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/AsyncResponses.java
kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/TopicsResource.java
kafka-rest/src/main/java/io/confluent/kafkarest/response/FakeAsyncResponse.java
kafka-rest/src/test/java/io/confluent/kafkarest/controllers/PartitionManagerImplTest.java
kafka-rest/src/test/java/io/confluent/kafkarest/controllers/TopicManagerImplTest.java
kafka-rest/src/test/java/io/confluent/kafkarest/integration/ClusterTestHarness.java
kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/TopicsResourceIntegrationTest.java
kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/TopicsResourceTest.java

This PR adds a endpoint to create topics:
* POST /v3/clusters/{clusterId}/topics
Not included here are Topic configurations at create-time. I will add that on follow-up PR.

CLIENTS-1503: Add CREATE Topics V3 endpoints.

---

kafka-rest/src/test/java/io/confluent/kafkarest/unit/JsonSchemaConverterTest.java

JsonSchemaUtils.toObject was fixed to return an envelope, the tests need to change accordingly.

DG-399 Fix tests due to JsonSchemaUtils change

---

kafka-rest/src/main/java/io/confluent/kafkarest/controllers/BrokerConfigManager.java
kafka-rest/src/main/java/io/confluent/kafkarest/controllers/BrokerConfigManagerImpl.java
kafka-rest/src/main/java/io/confluent/kafkarest/controllers/ControllersModule.java
kafka-rest/src/main/java/io/confluent/kafkarest/entities/BrokerConfig.java
kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/BrokerConfigData.java
kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/GetBrokerConfigResponse.java
kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/ListBrokerConfigsResponse.java
kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/BrokerConfigsResource.java
kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/BrokersResource.java
kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/V3ResourcesFeature.java
kafka-rest/src/test/java/io/confluent/kafkarest/controllers/BrokerConfigManagerImplTest.java
kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/BrokerConfigsResourceIntegrationTest.java
kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/BrokerConfigResourceTest.java

This PR adds endpoints to list and get Broker Configurations:
- LIST: GET /v3/clusters/{clusterId}/brokers/{brokerId}/configurations
- GET: GET /v3/clusters/{clusterId}/brokers/{brokerId}/configurations/{name}
Added unit tests for resource and manager classes.
Added integration test for BrokerConfigsResource.

CLIENTS-1501: Add broker configs endpoints

---

kafka-rest/src/main/java/io/confluent/kafkarest/controllers/CompletableFutures.java
kafka-rest/src/main/java/io/confluent/kafkarest/controllers/ReplicaManager.java
kafka-rest/src/main/java/io/confluent/kafkarest/controllers/ReplicaManagerImpl.java
kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/ReplicaData.java
kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/BrokersResource.java
kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/SearchReplicasByBrokerAction.java
kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/V3ResourcesFeature.java
kafka-rest/src/test/java/io/confluent/kafkarest/controllers/ReplicaManagerImplTest.java
kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/BrokersResourceIntegrationTest.java
kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/SearchReplicasByBrokerActionIntegrationTest.java
kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/BrokersResourceTest.java
kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/SearchReplicasByBrokerActionTest.java

Example Request:
```
GET /clusters/{clusterId}/brokers/{brokerId}/partition-replicas
```
Example Response:
```
{
"links": {
"self": "http://localhost:44757/v3/clusters/jZoxgdt6S9a8kRLG6pEHTg/brokers/0/partition-replicas",
"next": null
},
"data": [
{
"id": "crn:///kafka=jZoxgdt6S9a8kRLG6pEHTg/topic=topic-1/partition=1/replica=0",
"links": {
"self": "http://localhost:44757/v3/clusters/jZoxgdt6S9a8kRLG6pEHTg/topics/topic-1/partitions/1/replicas/0"
},
"attributes": {
"cluster_id": "jZoxgdt6S9a8kRLG6pEHTg",
"topic_name": "topic-1",
"partition_id": 1,
"broker_id": 0,
"is_leader": false,
"is_in_sync": true
},
"relationships": {
"broker": {
"links": {
"related": "http://localhost:44757/v3/clusters/jZoxgdt6S9a8kRLG6pEHTg/brokers/0"
}
}
},
"type": "KafkaReplica"
},
{
"id": …
```

Add find partition replicas by broker id endpoint.

---

kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/PartitionData.java

Currently its private which is inconsistent with the other Data attributes.

Make ParititonData public

---

kafka-rest/pom.xml
kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestApplication.java
pom.xml

Also move a dependency from parent pom to child pom.

Open visibility of configurePre/PostResourceHandling.

---

kafka-rest/src/main/java/io/confluent/kafkarest/entities/Cluster.java

Preparation for https://github.com/confluentinc/kafka-rest/pull/679.

Add static factory to Cluster.

---

kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestApplication.java
kafka-rest/src/main/java/io/confluent/kafkarest/controllers/AclManager.java
kafka-rest/src/main/java/io/confluent/kafkarest/controllers/AclManagerImpl.java
kafka-rest/src/main/java/io/confluent/kafkarest/controllers/ControllersModule.java
kafka-rest/src/main/java/io/confluent/kafkarest/entities/Acl.java
kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/AclData.java
kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/AclDataList.java
kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/CreateAclRequest.java
kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/DeleteAclsResponse.java
kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/Resource.java
kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/SearchAclsResponse.java
kafka-rest/src/main/java/io/confluent/kafkarest/extension/EnumConverterProvider.java
kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/AclsResource.java
kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/V3ResourcesFeature.java
kafka-rest/src/main/java/io/confluent/kafkarest/response/FakeUrlFactory.java
kafka-rest/src/main/java/io/confluent/kafkarest/response/UrlBuilder.java
kafka-rest/src/main/java/io/confluent/kafkarest/response/UrlFactory.java
kafka-rest/src/main/java/io/confluent/kafkarest/response/UrlFactoryImpl.java
kafka-rest/src/test/java/io/confluent/kafkarest/controllers/AclManagerImplTest.java
kafka-rest/src/test/java/io/confluent/kafkarest/integration/ClusterTestHarness.java
kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/AclsResourceIntegrationTest.java
kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/AclsResourceTest.java
testing/environments/sasl_plain/README.md
testing/environments/sasl_plain/docker-compose.yml
testing/environments/sasl_plain/run.sh
testing/image/bin/entrypoint.sh

* Search: `/v3/clusters/{clusterId}/acls?resource_type={resourceType}&resource_name={resourceName}&pattern_type={patternType}&principal={principal}&host={host}&operation={operation}&permission={permission}`
* Create: `/v3/clusters/{clusterId}/acls`
```
{
"resource_type": "{resourceType}",
"resource_name": "{resourceName}",
"pattern_type": "{patternType}",
"principal": "{principal}",
"host": "{host}",
"operation": "{operation}",
"permission": "{permission}"
}
```
* Delete: `/v3/clusters/{clusterId}/acls?resource_type={resourceType}&resource_name={resourceName}&pattern_type={patternType}&principal={principal}&host={host}&operation={operation}&permission={permission}`
All query parameters for Search and Delete are optional. Delete returns the deleted ACLs. Valid values for the parameters …

Add search/create/delete ACLs APIs.

---

kafka-rest/src/main/java/io/confluent/kafkarest/common/CompletableFutures.java
kafka-rest/src/test/java/io/confluent/kafkarest/common/CompletableFuturesTest.java

Usage:
```
catchingCompose(
future,
MyException.class,
myException -> doSomethingWithMyException(myException));
```

CNKAF-951: Add catchingCompose utility to handle exceptions.

---

kafka-rest/src/main/java/io/confluent/kafkarest/entities/ClusterConfig.java
kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/ClusterData.java
kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/ClustersResource.java
kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/ClustersResourceIntegrationTest.java
kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/ClustersResourceTest.java

Cluster-wide topic configs don't exist, never did, and likely never will. :)

Remove cluster-wide topic configs.

---

api/v3/kafka-rest-v3-spec.yaml

Grammar edits for the V3 config.

DOCS-4640 - Edit V3 Kafka REST config

---

kafka-rest/src/assembly/package.xml

See https://github.com/confluentinc/kafka-rest/pull/737.

KC-613: Remove share/java/kafka-rest dependencySet.

---

kafka-rest/src/main/java/io/confluent/kafkarest/v2/KafkaConsumerReadTask.java
kafka-rest/src/main/java/io/confluent/kafkarest/v2/KafkaConsumerState.java

Backport #766 to 5.2.x. Changes can't be cleanly cherrypicked because many things changed in 5.5.0 (files moved around and stuff).

RM-39: Backport #766 to 5.2.x.

---

kafka-rest/src/main/java/io/confluent/kafkarest/v2/KafkaConsumerReadTask.java
kafka-rest/src/main/java/io/confluent/kafkarest/v2/KafkaConsumerState.java

Backport #766 to 5.4.x. Changes can't be cleanly cherrypicked because many things changed in 5.4.0 and 5.5.0 (files moved around and stuff).

RM-39: Backport #766 to 5.4.x.

---

testing/environments/minimal/run.sh
testing/environments/mtls/README.md
testing/environments/mtls/run.sh

Fix mtls test env run script.

---

api/v3/openapi.yaml
kafka-rest/src/main/java/io/confluent/kafkarest/controllers/BrokerConfigManager.java
kafka-rest/src/main/java/io/confluent/kafkarest/controllers/BrokerConfigManagerImpl.java
kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/BrokerConfigsResource.java
kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/ListAllBrokersConfigsAction.java
kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/ListAllTopicsConfigsAction.java
kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/V3ResourcesFeature.java
kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/ListAllBrokersConfigsActionIntegrationTest.java
kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/ListAllTopicsConfigsActionIntegrationTest.java
kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/ListAllBrokersConfigsActionTest.java

Adds a new endpoint - /v3/clusters/{clusterId}/brokers/-/configs
**What**
Fetches configuration for all brokers in the cluster.

MMA-10463: list all broker configs

---

debian/Makefile

Support new security patch release pattern.
Add new security suffix for packaging name.

security patch release support

---

api/v3/openapi.yaml

Description:
- https://confluentinc.atlassian.net/browse/DOCS-8602
- https://confluentinc.atlassian.net/browse/KREST-728
- Related PR: #858 
Signed-off-by: Victoria Bialas <vicky@confluent.io>

KREST-728, DOCS-8602 Corrections to Produce v3 OpenAPI #858

---

api/v3/openapi.yaml

- https://confluentinc.atlassian.net/browse/DOCS-8602
- https://confluentinc.atlassian.net/browse/KREST-728
- #858
- #865
Signed-off-by: Victoria Bialas <vicky@confluent.io>

DOCS-8602, KREST-728 Cherry-pick #858 from 6.2.x to 6.2.0-post, add copyedits

---

kafka-rest/src/main/java/io/confluent/kafkarest/tools/ConsumerPerformance.java

ironcally we also need to suppress the warning due to
spotbugs/spotbugs#1539

fix issues identified by spotbugs

---

kafka-rest/src/main/java/io/confluent/kafkarest/extension/MorePriorities.java
kafka-rest/src/main/java/io/confluent/kafkarest/resources/v2/ConsumersResource.java

fixes for upcoming changes in https://github.com/confluentinc/common/pull/364

fix formatting issues with newer checkstyle versions

---

kafka-rest/src/main/java/io/confluent/kafkarest/backends/kafka/KafkaModule.java

See https://github.com/confluentinc/kafka-rest/pull/875 for context.

Add KAFKA_REST_CONTEXT_PROPERTY_NAME constant.

---

kafka-rest/src/test/java/io/confluent/kafkarest/integration/ConsumerTimeoutTest.java

KREST-4785 Spotless fail after pint merge from 6.0.x

---

api/v3/openapi.yaml

"raw_schema" in ProduceRequestData must be just "schema".

KREST-4291 Fix an issue in Produce v3 docs

---

kafka-rest/src/main/java/io/confluent/kafkarest/DefaultKafkaRestContext.java
kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestContext.java
kafka-rest/src/test/java/io/confluent/kafkarest/integration/KafkaModuleOverridingTest.java

Remove KafkaRestContext#getProducerPool.

---

kafka-rest/src/main/java/io/confluent/kafkarest/v2/KafkaConsumerState.java

Hi, just replaced the deprecated method with the new one. Best regards :)
Originally we were working on: #432

replaced deprecated method

---

api/v3/openapi.yaml
kafka-rest/pom.xml
kafka-rest/src/main/java/io/confluent/kafkarest/controllers/TopicManager.java
kafka-rest/src/main/java/io/confluent/kafkarest/controllers/TopicManagerImpl.java
kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/PartitionCountRequest.java
kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/PartitionsCountRequest.java
kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/TopicsResource.java
kafka-rest/src/test/java/io/confluent/kafkarest/controllers/TopicManagerImplTest.java
kafka-rest/src/test/java/io/confluent/kafkarest/integration/ClusterTestHarness.java
kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/TopicsResourceIntegrationTest.java
kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/TopicsResourceTest.java
pom.xml

Squashed commit so I can cherry pick more easily to the cloud release branch

KREST-3009 Add the ability to increase num.partitions on a topic

---

kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/TopicsResource.java

Calling get on a topic manager twice, when running in Confluent cloud, results in a Out Of Scope Exception
I'm not sure why this is - I wonder if it runs slower in this environment and as the call is async, the scope has been lost by the time the first async call to update the partition count returns, ready for us to get the topic information in the response.

KREST-8639 Only call get on topic manager provider once

---

kafka-rest/src/main/java/io/confluent/kafkarest/v2/KafkaConsumerState.java

Cherry pick #1112

---

kafka-rest/src/test/java/io/confluent/kafkarest/ratelimit/FixedCostRateLimitFeatureTest.java

https://confluentinc.atlassian.net/browse/KREST-3850

KREST-9229 Disable flaky test

---

api/v3/openapi.yaml

Add missing `include_authorized_operations` query parameter and `authorized_operations` to the `TopicData` schema to match the code.

KREST-7599 - add authorized_operations

---

api/v3/openapi.yaml

Spec runs through a variety of validations tools. Generated documentation is clean too.

OpenAPI specification validation fixes

---

api/v3/openapi.yaml

Consistency of terminology improved in descriptions.

KREST-5471 Tidy up descriptions of API operations

---

api/v3/openapi.yaml

Produce v3 is now generally available.

KREST-9559 Update lifecycle for Produce v3

---

kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestConfig.java
kafka-rest/src/main/java/io/confluent/kafkarest/config/ConfigModule.java
kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/ProduceBatchAction.java
kafka-rest/src/main/java/io/confluent/kafkarest/response/StreamingResponse.java
kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/ProduceBatchActionIntegrationTest.java
kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/ProduceBatchActionTest.java

A few enhancements:
* Order of batch response entries now matches the request entries
* Same exception handling as streaming produce
* Configurable maximum batch size

KREST-10639 Tidy up batch produce

---

kafka-rest/src/test/java/io/confluent/kafkarest/exceptions/KafkaRestExceptionMapperTest.java

 KREST-10790 Add test for KafkaRestExceptionMapper.java

---

api/v3/openapi.yaml

https://confluentinc.atlassian.net/browse/DOCS-24704

KREST-11122 - Add note about empty response from endpoint

---

kafka-rest/pom.xml
pom.xml

This is an autogenerated pull request by `pint` due to a merge conflict failure seen during [`pint merge`](http://go/pint-merge-service).
1. Resolve all conflicts (either via web editor or the command line)
2. Commit merge
3. Obtain approvals from reviewers
4. **(IMPORTANT)** After obtaining approvals, click the dropdown menu on the merge button and select **"Create a merge commit"** 
5. Click the "Merge pull request" button
6. Re-run [`pint merge`]( http://go/pint-merge-service)
NOTE: **"Create a merge commit"** option must be used to ensure all commits from the head branch is added to the base branch.
Please reach out to the Developer Productivity team on Slack at #devprod-eng or #devprod-oncall

Merge Conflict Resolution (from 7.4.x to 7.5.x)

---

api/v3/openapi.yaml

Add error coded 400, 415 to spec.

KREST-11195 Fix REST produce docs

---

kafka-rest/src/main/java/io/confluent/kafkarest/Errors.java

* Adding an error code for the consumer group id not found

KREST-10009, Adding an error code for the consumer group id not found

---

Jenkinsfile
service.yml

You will need to run service-bot and merge the PR it creates. [See the instructions](https://confluentinc.atlassian.net/wiki/spaces/TOOLS/pages/3211693075/Jenkins+-+Semaphore+self+migration+guide#How-do-I-apply-changes-from-service.yml?)  
If applicable, [apply these changes to release branches](https://confluentinc.atlassian.net/wiki/spaces/TOOLS/pages/3211693075/Jenkins+-+Semaphore+self+migration+guide#I-only-see-changes-for-master.-How-do-I-apply-to-release-branches%3F)
This PR is the first step in migrating this repo from Jenkins to Semaphore.  
Once you see things are running smoothly on Semaphore for this repo, open a follow-up PR to delete the Jenkinsfile.  
This PR does two things:
1) Disables jenkins deploy.
2) Sets up cc-service-bot to create a semaphore.yaml. -> Expect a PR …

Migration: Jenkins -> Semaphore

---

kafka-rest/pom.xml
pom.xml

This PR upgrade dependencies to versions that fixe CVE-2023-33201
There will be pint merge following up after this.

KREST-12372 Upgrade dependency to JDK 1.8 with version 1.77 

---

api/v3/openapi.yaml

These are the CP changes requested.

KNET-13676 - `cluster_id` is not validated [cp version]

---

kafka-rest/src/main/java/io/confluent/kafkarest/SystemTime.java

Cherry-picked https://github.com/confluentinc/kafka-rest/pull/1276 to master.

Fix SystemTime and revert pin ak version

---

kafka-rest/src/main/java/io/confluent/kafkarest/v2/KafkaConsumerState.java

PR in airlock repo: https://github.com/confluentinc/airlock-kafka-rest/pull/18

Fix rest build due to upstream changes in ce-kafka

---

kafka-rest/pom.xml
pom.xml

This is an autogenerated pull request by `pint` due to a merge conflict failure seen during [`pint merge`](http://go/pint-merge-service).
1. Resolve all conflicts (either via web editor or the command line)
2. Commit merge
3. Obtain approvals from reviewers
4. **(IMPORTANT)** After obtaining approvals, click the dropdown menu on the merge button and select **"Create a merge commit"** 
5. Click the "Merge pull request" button
6. Re-run [`pint merge`]( http://go/pint-merge-service)
NOTE: **"Create a merge commit"** option must be used to ensure all commits from the head branch is added to the base branch.
Please reach out to the Developer Productivity team on Slack at #devprod-eng or #devprod-oncall

Merge Conflict Resolution (from 7.5.x to 7.6.x)

---

kafka-rest/pom.xml

PR to master for https://github.com/confluentinc/kafka-rest/pull/1336

Exclude log4j2 deps from kafka

---

kafka-rest/src/main/java/io/confluent/kafkarest/requestlog/GlobalDosFilterListener.java
kafka-rest/src/main/java/io/confluent/kafkarest/requestlog/PerConnectionDosFilterListener.java

rest-utils is updating the 7.9.x branch to include changes to DosFilter - https://github.com/confluentinc/rest-utils/pull/536
this PR resolves build errors that would've occurred

[7.9.x] Use Confluent package for DosFilter

---

kafka-rest/src/main/java/io/confluent/kafkarest/requestlog/GlobalDosFilterListener.java
kafka-rest/src/main/java/io/confluent/kafkarest/requestlog/PerConnectionDosFilterListener.java

rest-utils is updating the 7.9.0 branch to include changes to DosFilter - https://github.com/confluentinc/rest-utils/pull/538
this PR resolves build errors that would've occurred

[7.9.0] Use Confluent package for DosFilter

---

config/log4j2.yaml
kafka-rest/src/test/resources/log4j2.yaml

Use %p for including log level in log output.

Fix log4j pattern config

---

config/kafka-rest.properties

Restore `#schema.registry.url=http://localhost:8081` property

restore property

---

NOTICE
checkstyle/import_control.xml
config/kafka-rest.properties
kafka-rest/src/main/java/io/confluent/kafkarest/Errors.java
kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestApplication.java
kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestConfig.java
kafka-rest/src/test/java/io/confluent/kafkarest/integration/AuthorizationErrorTest.java
kafka-rest/src/test/java/io/confluent/kafkarest/integration/ClusterTestHarness.java
kafka-rest/src/test/java/io/confluent/kafkarest/integration/ConsumerTimeoutTest.java
kafka-rest/src/test/java/io/confluent/kafkarest/integration/MetadataApiTest.java
kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/ClustersResourceIntegrationTest.java
kafka-rest/src/test/java/io/confluent/kafkarest/testing/QuorumControllerFixture.java
licenses/NOTICE.confluent-common.txt
licenses/NOTICE.confluent-schema-registry.txt
pom.xml
testing/environments/minimal/README.md
testing/environments/minimal/docker-compose.yml
testing/environments/minimal/run.sh
testing/environments/mtls/README.md
testing/environments/mtls/docker-compose.yml
testing/environments/mtls/run.sh
testing/environments/sasl_plain/README.md
testing/environments/sasl_plain/docker-compose.yml
testing/environments/sasl_plain/kafka-jaas.conf
testing/environments/sasl_plain/run.sh
testing/environments/sasl_plain/zookeeper-jaas.conf

remove zk references to support CP 8.0.X release

remove zk references

---

kafka-rest/pom.xml
pom.xml

We need to keep minor version the same with branch name. Hence revert previous version bump PR(#1389)

[revert] cherry pick fa71840

---

kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestApplication.java

Community/open-source deployments won't be offered enterprise support.

KNET-19822: Prompt for community/open-source editions
