src/test/java/io/confluent/kafkarest/integration/AbstractConsumerTest.java, src/test/java/io/confluent/kafkarest/integration/AvroProducerTest.java, src/test/java/io/confluent/kafkarest/integration/ClusterTestHarness.java, src/test/java/io/confluent/kafkarest/integration/ConsumerAvroTest.java, src/test/java/io/confluent/kafkarest/integration/MetadataAPITest.java, src/test/java/io/confluent/kafkarest/integration/ProducerTest.java
Reduce integration test time by using fewer brokers, one most of the time, and
only starting the schema registry when required. Fixes #62.
=> Reduce integration test time.

bin/kafka-rest-run-class
The packaging intentionally pulls in a copy of the Kafka jars so that kafka-rest
doesn't need Scala versioning. The inclusion of the Kafka directory was leftover
from before our packaging setup supported different Scala versions of
Kafka. Fixes #77.
=> Remove kafka from list of production directories to include in CLASSPATH.

docs/monitoring.rst, pom.xml
Updates the documentation and JUnit version.
I am not sure how we want to format deprecations, so this is just something to start the conversation.
Should follow https://github.com/confluentinc/rest-utils/pull/21
=> rest-utils updates

docs/intro.rst
The docs currently say that a broker is expected to be running on localhost:9092. This isn't true. A broker doesn't need to be running on localhost:9092, and a bootstrap list of brokers doesn't need to be configured, either.
=> Doc change to remove the expectation that a broker is running on localhost:9092.

docs/monitoring.rst
Commit for #229
I'm not of the correct way to document these metrics.  There isn't really any public documentation available on the specifics on what Jetty is actually exposing so I'm not sure if this is the right place to do it.  It exposes a lot of different beans and attributes so it would be cumbersome to list them out here.
I took the tack of providing a hint for users that the data is indeed there and can be discovered via jconsole/visualvm/whatever.
=> Issue #229: Add blurb on Jetty jmx metrics

src/main/java/io/confluent/kafkarest/AvroRestProducer.java, src/test/java/io/confluent/kafkarest/unit/AvroRestProducerTest.java
Added a map in the avrorestproducer that will cache schemas and return the id if there is one for that schema rather than reregistering.
=> fixing issue #91

bin/kafka-rest-run-class
=> fix typo command line options `-help` check

docs/intro.rst
Link to configuration settings was linking to schema registry configs instead of REST proxy.
=> Incorrect link in documentation

src/test/java/io/confluent/kafkarest/TestUtils.java, src/test/java/io/confluent/kafkarest/integration/AbstractConsumerTest.java, src/test/java/io/confluent/kafkarest/integration/AbstractProducerTest.java, src/test/java/io/confluent/kafkarest/integration/AvroProducerTest.java, src/test/java/io/confluent/kafkarest/integration/MetadataAPITest.java, src/test/java/io/confluent/kafkarest/unit/BrokersResourceTest.java, src/test/java/io/confluent/kafkarest/unit/ConsumerResourceAvroTest.java, src/test/java/io/confluent/kafkarest/unit/ConsumerResourceBinaryTest.java, src/test/java/io/confluent/kafkarest/unit/ConsumerResourceTest.java, src/test/java/io/confluent/kafkarest/unit/PartitionsResourceAvroConsumeTest.java, src/test/java/io/confluent/kafkarest/unit/PartitionsResourceAvroProduceTest.java, src/test/java/io/confluent/kafkarest/unit/PartitionsResourceBinaryConsumeTest.java, src/test/java/io/confluent/kafkarest/unit/PartitionsResourceBinaryProduceTest.java, src/test/java/io/confluent/kafkarest/unit/PartitionsResourceTest.java, src/test/java/io/confluent/kafkarest/unit/RootResourceTest.java, src/test/java/io/confluent/kafkarest/unit/TopicsResourceAvroProduceTest.java, src/test/java/io/confluent/kafkarest/unit/TopicsResourceBinaryProduceTest.java, src/test/java/io/confluent/kafkarest/unit/TopicsResourceTest.java
This will aid in debugging when unexpected responses are received.
=> CLIENTS-304: Add test utility that logs entities if they fail to parse.

src/test/java/io/confluent/kafkarest/integration/ProducerTest.java
This also uses the field defined in ProducerConfig instead of the string constant so we'll see any future deprecation
warnings.
=> CLIENTS-305: Use max.block.ms instead of metadata.fetch.timeout.ms since the latter was deprecated and now removed in KAFKA-3763

docs/api.rst, src/main/java/io/confluent/kafkarest/AvroConsumerState.java, src/main/java/io/confluent/kafkarest/BinaryConsumerState.java, src/main/java/io/confluent/kafkarest/JsonConsumerState.java, src/main/java/io/confluent/kafkarest/SimpleConsumerManager.java, src/main/java/io/confluent/kafkarest/entities/AvroConsumerRecord.java, src/main/java/io/confluent/kafkarest/entities/BinaryConsumerRecord.java, src/main/java/io/confluent/kafkarest/entities/ConsumerRecord.java, src/main/java/io/confluent/kafkarest/entities/JsonConsumerRecord.java, src/test/java/io/confluent/kafkarest/mock/MockConsumerQueue.java, src/test/java/io/confluent/kafkarest/unit/ConsumerManagerTest.java, src/test/java/io/confluent/kafkarest/unit/ConsumerResourceAvroTest.java, src/test/java/io/confluent/kafkarest/unit/ConsumerResourceBinaryTest.java, src/test/java/io/confluent/kafkarest/unit/PartitionsResourceAvroConsumeTest.java, src/test/java/io/confluent/kafkarest/unit/PartitionsResourceBinaryConsumeTest.java
AvroConsumerRecord had two constructors with @JsonProperty parameters which caused it to sometimes fail to properly
deserialize. Additionally, adding the topic field to ConsumerRecord for the v2 API resulted in null entries in the v1
API. This is confusing; instead, we should be filling that in since it is a backwards compatible addition and keeps the
output uniform.
=> CLIENTS-304: Fix AvroConsumerRecord constructors and handling of topic for v1 consumer API.

pom.xml
The dependency was presumably lost during refactoring to share the common pom
=> CLIENTS-491: Restore log4j dependency

src/main/java/io/confluent/kafkarest/converters/AvroConverter.java
Duplicate "else if" block because line 135 already checks `instanceof GenericContainer`.
Caught by IntelliJ.
=> Tiny code simplification

checkstyle/suppressions.xml, config/kafka-rest.properties, src/main/java/io/confluent/kafkarest/AdminClientWrapper.java, src/main/java/io/confluent/kafkarest/DefaultKafkaRestContext.java, src/main/java/io/confluent/kafkarest/KafkaRestApplication.java, src/main/java/io/confluent/kafkarest/KafkaRestConfig.java, src/main/java/io/confluent/kafkarest/KafkaRestContext.java, src/main/java/io/confluent/kafkarest/MetadataObserver.java, src/main/java/io/confluent/kafkarest/ProducerPool.java, src/main/java/io/confluent/kafkarest/UnsupportedMetaDataObserver.java, src/main/java/io/confluent/kafkarest/extension/KafkaRestContextProvider.java, src/main/java/io/confluent/kafkarest/resources/BrokersResource.java, src/main/java/io/confluent/kafkarest/resources/PartitionsResource.java, src/main/java/io/confluent/kafkarest/resources/TopicsResource.java, src/main/java/io/confluent/kafkarest/resources/v2/PartitionsResource.java, src/main/java/io/confluent/kafkarest/v2/KafkaConsumerManager.java, src/test/java/io/confluent/kafkarest/integration/MetadataAPITest.java, src/test/java/io/confluent/kafkarest/integration/ProducerTest.java, src/test/java/io/confluent/kafkarest/integration/TestKafkaRestApplication.java, src/test/java/io/confluent/kafkarest/unit/AbstractConsumerResourceTest.java, src/test/java/io/confluent/kafkarest/unit/BrokersResourceTest.java, src/test/java/io/confluent/kafkarest/unit/PartitionsResourceAbstractConsumeTest.java, src/test/java/io/confluent/kafkarest/unit/PartitionsResourceAvroProduceTest.java, src/test/java/io/confluent/kafkarest/unit/PartitionsResourceBinaryProduceTest.java, src/test/java/io/confluent/kafkarest/unit/PartitionsResourceTest.java, src/test/java/io/confluent/kafkarest/unit/RootResourceTest.java, src/test/java/io/confluent/kafkarest/unit/TopicsResourceAvroProduceTest.java, src/test/java/io/confluent/kafkarest/unit/TopicsResourceBinaryProduceTest.java, src/test/java/io/confluent/kafkarest/unit/TopicsResourceTest.java, src/test/java/io/confluent/kafkarest/v2/KafkaConsumerManagerTest.java
- Uses Admin Client instead of ZkUtils for all metadata API
- It is required to configure at least one of ZK connect url or boot strap brokers
- V1 Consumer API would work only if ZK connect URL is configured
- No proactive checks to topic exists or partition exists as that would require additional ACL's to be defined for the producer user. Making config easier compared to super friendly response message & code
=> CLIENTS-512 - Use Admin Client instead of ZkUtils for all metadata API

src/test/java/io/confluent/kafkarest/integration/AvroProducerTest.java, src/test/java/io/confluent/kafkarest/integration/ClusterTestHarness.java, src/test/java/io/confluent/kafkarest/integration/ConsumerAvroTest.java, src/test/java/io/confluent/kafkarest/integration/ConsumerBinaryTest.java, src/test/java/io/confluent/kafkarest/integration/ConsumerJsonTest.java, src/test/java/io/confluent/kafkarest/integration/ConsumerTimeoutTest.java, src/test/java/io/confluent/kafkarest/integration/JsonProducerTest.java, src/test/java/io/confluent/kafkarest/integration/MetadataAPITest.java, src/test/java/io/confluent/kafkarest/integration/ProducerTest.java, src/test/java/io/confluent/kafkarest/integration/SimpleConsumerAvroTest.java, src/test/java/io/confluent/kafkarest/integration/SimpleConsumerBinaryTest.java, src/test/java/io/confluent/kafkarest/integration/SimpleConsumerJsonTest.java
This fixes build breakage caused by
https://github.com/apache/kafka/commit/89b245baa7963e908d5f22d6f53c34f14690af67
=> Use KafkaZkClient instead of ZkUtils in tests

docs/intro.rst
Fix wrong link in kafka rest doc
https://confluentinc.atlassian.net/browse/DOCS-339
=> DOCS-339 - Fix config hyperlink

src/main/java/io/confluent/kafkarest/extension/KafkaRestContextProvider.java
CLIENTS-512 made the ZkUtils in KafkaRestContextProvider optional, but the
clean() method was still assuming it was always set.
=> Check if defaultZkUtils is null before closing.

kafka-rest/src/test/java/io/confluent/kafkarest/unit/PartitionsResourceAvroProduceTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/unit/PartitionsResourceBinaryProduceTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/unit/TopicsResourceAvroProduceTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/unit/TopicsResourceBinaryProduceTest.java
This constructor has been removed in Apache Kafka 2.0.
=> Don't use deprecated RecordMetadata constructor

kafka-rest/pom.xml
The Scala consumers have been removed from Apache Kafka and
this change gets the build working again. I will submit
another pull request that makes things work with Kafka 2.0.
=> Temporarily pin Kafka and Confluent versions

bin/kafka-rest-run-class
Producing to a topic with REST proxy fails in CP with `ClassNotFoundException`. This is because monitoring interceptors are not included in the CLASSPATH. Verified that the patch works as expected on confluent-5.0.0-SNAPSHOT.
```
$ bin/confluent start kafka-rest
This CLI is intended for development only, not for production
https://docs.confluent.io/current/cli/index.html
Using CONFLUENT_CURRENT: /var/folders/sp/24h2p81j4zvcg73d1z25rfym0000gp/T/confluent.Hh6OHtnY
Starting zookeeper
zookeeper is [UP]
Starting kafka
kafka is [UP]
Starting schema-registry
schema-registry is [UP]
Starting kafka-rest
kafka-rest is [UP]
$ curl -X POST -H "Content-Type: application/vnd.kafka.json.v2+json" \
>       -H "Accept: application/vnd.kafka.v2+json" \
>       --data '{"records":[{"value":{"foo":"bar"}}]}' …
```
=> PLAT-77: Include monitoring-interceptors in CLASSPATH

debian/confluent-kafka-rest.spec.in, docs/index.rst
Also for [DOCS-684](https://confluentinc.atlassian.net/browse/DOCS-684).
=> DOCS-627: Rename Confluent Kafka REST Proxy to Confluent REST Proxy

docs/index.rst
Add connecting to ccloud to nav.
=> DOCS-630 - Add CCloud link to nav

kafka-rest/src/main/java/io/confluent/kafkarest/AdminClientWrapper.java
Original Kafka error message were lost in the AdminClientWrapper.
Before the fix:
```shell
$ curl http://kafka-rest.local/topics/my_topic
{"error_code":50002,"message":"Kafka error: "}
```
With the fix:
```shell
$ curl http://kafka-rest.local/topics/my_topic
{"error_code":50002,"message":"Kafka error: org.apache.kafka.common.errors.TopicAuthorizationException: Not authorized to access topics: [Topic authorization failed.]"} 
```
=> Fix missing cause error message for Kafka errors

docs/config.rst, docs/deployment.rst, kafka-rest/src/main/java/io/confluent/kafkarest/ConsumerManager.java, kafka-rest/src/main/java/io/confluent/kafkarest/ConsumerReadTask.java, kafka-rest/src/main/java/io/confluent/kafkarest/ConsumerWorker.java, kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestConfig.java, kafka-rest/src/main/java/io/confluent/kafkarest/v2/KafkaConsumerManager.java, kafka-rest/src/main/java/io/confluent/kafkarest/v2/KafkaConsumerReadTask.java, kafka-rest/src/main/java/io/confluent/kafkarest/v2/KafkaConsumerWorker.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/AbstractConsumerTest.java, pom.xml
Since we went with a slightly different model for consumer threading in 4.0 (https://github.com/confluentinc/kafka-rest/pull/476), we are going to be merging that upstream to 5.0.x and trunk. The merge would be cleaner if we first reverted the previous changes
=> Revert Consumer Threading 5.0

kafka-rest/src/main/java/io/confluent/kafkarest/SimpleConsumerManager.java
Fixed bug where the API would return the incorrect offset when specific offset was requested and the topic was compressed. The SimpleConsumerManager assumed the first offset in the returned MessageSet was the requested offset, this is not necessarily the case with compressed formats.
See bug #475
=> Fix SimpleConsumerManager properly return requested offsets for compressed topic

kafka-rest/pom.xml
Change to use ${project.version}
- Standardized to use project.version instead of hard coded version.
- This is failing bumps for kafka-rest.
=> Change to use ${project.version}

kafka-rest/src/main/java/io/confluent/kafkarest/AdminClientWrapper.java, kafka-rest/src/main/java/io/confluent/kafkarest/DefaultKafkaRestContext.java, kafka-rest/src/test/java/io/confluent/kafkarest/unit/AdminClientWrapperTest.java
Originally reported in https://github.com/confluentinc/kafka-rest/issues/410
No unit tests exist to test the `AdminClientWrapper`. It is currently not easy to test it since it instantiated its own `AdminClient` and does not have it passed it.
Do comment if you think it is worth it to rework the code to support some mock tests
=> CPKAFKA-1794: Assign leader ID -1 on offline partitions in the topic describe API

src/main/java/io/confluent/kafkarest/ConsumerManager.java, src/main/java/io/confluent/kafkarest/ConsumerState.java, src/main/java/io/confluent/kafkarest/v2/KafkaConsumerManager.java, src/main/java/io/confluent/kafkarest/v2/KafkaConsumerState.java, src/test/java/io/confluent/kafkarest/integration/ConsumerTimeoutTest.java
The REST Proxy has a memory leak in maintaining one data structure.
Its `consumersByExpiration` priority queue is supposed to track the consumer that is closest to expiry. There is a separate `ExpirationThread` that monitors this structure and deletes a consume if it has expired.
We update a consumer's expiration and add it back to the queue (so it can re-order itself) on every `poll()` call. The root problem is that we do not remove the old consumer instance from the queue. This results in a `consumersByExpiration` structure with huge sizes, since `poll()` is called very often, especially when consuming high volumes of records. (max.poll.records is set to 30 by default) Even worse, the proxy is currently configured to `poll()` repeatedly with a timeout of 50ms until the default consume …
=> CPKAFKA-1865:  Performance degrades drastically after running for extended periods

kafka-rest/src/main/java/io/confluent/kafkarest/ConsumerManager.java, kafka-rest/src/main/java/io/confluent/kafkarest/v2/KafkaConsumerManager.java
The problem originates from the `getDelay` implementation here:
https://github.com/confluentinc/kafka-rest/blob/2928ac85ae77d2350c774271c5c6d4ae0d34c317/kafka-rest/src/main/java/io/confluent/kafkarest/v2/KafkaConsumerManager.java#L389
We want each read task to be delayed for at least 50 milliseconds but the conversion done there takes the 50 milliseconds leftover as nanoseconds and converts them to milliseconds (returning 0). This causes the ReadTaskSchedulerThread to use more CPU than needed by looping read tasks and calling `poll()` too often
=> CPKAFKA-1871: Fix problem where ReadTaskSchedulerThread would loop too often

kafka-rest/src/test/java/io/confluent/kafkarest/unit/AbstractConsumerResourceTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/unit/ConsumerManagerTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/unit/PartitionsResourceAbstractConsumeTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/unit/PartitionsResourceAvroProduceTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/unit/PartitionsResourceBinaryProduceTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/unit/TopicsResourceAvroProduceTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/unit/TopicsResourceBinaryProduceTest.java
methods have been removed in easymock 4.x
=> remove usage of deprecated easymock methods

kafka-rest/src/main/java/io/confluent/kafkarest/ConsumerManager.java, kafka-rest/src/main/java/io/confluent/kafkarest/ConsumerState.java, kafka-rest/src/main/java/io/confluent/kafkarest/v2/KafkaConsumerManager.java, kafka-rest/src/main/java/io/confluent/kafkarest/v2/KafkaConsumerState.java, kafka-rest/src/test/java/io/confluent/kafkarest/unit/ConsumerManagerTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/v2/KafkaConsumerManagerTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/v2/LoadTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/v2/MockConsumer.java
This PR adds:
* tests verifying that the `DelayQueue<RunnableReadTask> delayedReadTasks` is populated
* tests verifying that `RunnableReadTask` delays are updated
* tests verifying that `backoff.ms` affects task re-schedules
* a bigger, integration-like load tests where we spawn 50 consumers and run for 1 minute
=> CPKAFKA-1868: Improve consumer tests

kafka-rest/src/main/java/io/confluent/kafkarest/ConsumerManager.java, kafka-rest/src/main/java/io/confluent/kafkarest/v2/KafkaConsumerManager.java
```  java 
this.executor = new KafkaConsumerThreadPoolExecutor(0, maxThreadCount,
60L, TimeUnit.SECONDS,
new SynchronousQueue<Runnable>(),
new RejectedExecutionHandler() {
@Override
public void rejectedExecution(Runnable r, ThreadPoolExecutor executor) {
log.debug("The runnable {} was rejected execution. "
+ "The thread pool must be satured or shutiing down", r);
if (r instanceof ReadFutureTask) {
ReadFutureTask readFutureTask = (ReadFutureTask) r;
RunnableReadTask readTask = (RunnableReadTask)readFutureTask.getReadTask();
readTask.delayFor(ThreadLocalRandom.current().nextInt(25, 76));
} else {
// run commitOffset and consumer close tasks from the caller thread
if (!executor.isShutdown()) {
r.run();
}
}
}
}
);
```   
in RejectedExecutionHandler the rejectedExecution method,the runnable is …
=> the ThreadPoolExecutor RejectedExecutionHandler was error

checkstyle/suppressions.xml, docs/api.rst, docs/config.rst, docs/deployment.rst, kafka-rest/src/main/java/io/confluent/kafkarest/ConsumerManager.java, kafka-rest/src/main/java/io/confluent/kafkarest/ConsumerReadTask.java, kafka-rest/src/main/java/io/confluent/kafkarest/Errors.java, kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestConfig.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/ConsumerInstanceConfig.java, kafka-rest/src/main/java/io/confluent/kafkarest/v2/KafkaConsumerManager.java, kafka-rest/src/main/java/io/confluent/kafkarest/v2/KafkaConsumerReadTask.java, kafka-rest/src/main/java/io/confluent/kafkarest/v2/KafkaConsumerState.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/AbstractConsumerTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/ConsumerBinaryTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/unit/ConsumerManagerTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/v2/KafkaConsumerManagerTest.java
This commit enables long-polling functionality in the V1 and V2 consumer APIs.
Previously, consumer.request.timeout.ms would control when the proxy sent back a response to the user. The default value was 1000ms, but setting it explicitly to 1000 (or 2000) would cause it to be passed to the underlying consumer connection. This caused a NullPointerException because configuration exceptions were ignored in the V2 API.
This PR stops the behavior of passing the consumer.request.timeout.ms to the underlying consumer.
The proxy now also raises exceptions and returns proper 4xx responses when the given V2 Consumer settings are invalid.
Adds a new config setting:
* fetch.min.bytes - the amount of bytes of records the proxy will collect before immediately returning a response. It is configurable …
=> CPKAFKA-1681:  Add long polling functionality

docs/api.rst
As discussed in #481 . @stanislavkozlovski please checkout whether my understanding of the current long polling logic is correct
=> ellaborate on /consumer/.../records timeout parameter

kafka-rest/pom.xml
This PR fixes an error we started getting with the new 2.2 AK version - 
```
java.lang.NoSuchMethodError: kafka.server.KafkaServer.dataPlaneRequestProcessor()Lkafka/server/KafkaApis;
at io.confluent.kafkarest.integration.AvroProducerTest.setUp(AvroProducerTest.java:127)
```
For some reason, the tests' `TestUtils` would receive a 1.1 version of the `KafkaServer` (without `KafkaServer#dataPlaneRequestProcessor`) whereas it used the 2.2 API - `KafkaServer#dataPlaneRequestProcessor()`
I am not exactly sure how this is possible and how that even works, considering they use the same namespace. Do we construct one version of `KafkaServer` in bytecode and expect another?
This change seems to fix the issue, though
https://confluent.slack.com/archives/C3226NBLJ/p1548554920773700 …
=> Pin org.apache.kafka version to 1.1 in tests

kafka-rest/src/test/java/io/confluent/kafkarest/integration/AbstractProducerTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/AvroProducerTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/ClusterTestHarness.java
- Add support to override SR properties in ClusterTestHarness
- Pass Query params to AbstractProducerTest methods
- Make AvroProducerTest test methods accessible in subclasses
=> Add support to override SR properties and make few tests extensible

debian/confluent-kafka-rest.service
Kafka rest proxy opens a lot of files while running. And systemd ignores the
open file limit in /etc/security/limits.conf.
So this change updates kafka-rest.service systemd service file that we
ship to increase open file descriptor limit by adding this line in
[Service] section:
LimitNOFILE=1000000
This sets both hard and soft limit for "the maximum number of open file
descriptors" the program will use. NOTE: If we want to set different
value for hard and soft limits, the syntax is "soft:hard".
=> CPKAFKA-2810: Update file descriptor limit to 1 million

kafka-rest/src/test/java/io/confluent/kafkarest/integration/ClusterTestHarness.java
Also addresses CPKAFKA-2591.
This PR just bumps the timeout for connecting to Zookeeper in ClusterTestHarness. There seemed to be multiple tests flaking due to:
```
kafka.zookeeper.ZooKeeperClientTimeoutException: Timed out waiting for connection while in state: CONNECTING
```
I ran the tests 20 times locally and could not reproduce the above error.
=> CPKAFKA-2590: Bump ZK connection timeout to avoid test flakes.

kafka-rest/src/test/java/io/confluent/kafkarest/integration/AuthorizationErrorTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/ClusterTestHarness.java
https://github.com/apache/kafka/pull/6728/commits/5c54538b7dbecec781cf0418cc1dc44923003753 changed the signature of `TestUtils.createBrokerConfig`, this change fixes calls to that method.
=> Fix call to TestUtil.createBrokerConfig

kafka-rest-scala-consumer/pom.xml
We have removed `zkclient` dependency from Kafka.  kafka-rest-scala-consumer depends on zk-client. This PR includes `zkclient` dependency to kafka-rest-scala-consumer shade jar.
=> MINOR: Include `zkclient` dependency to kafka-rest-scala-consumer shaded jar

Jenkinsfile
As per the new Slack changes we want all the notifications from bots
which are not immediately actionable to go to a different channel. Moving
the jenkins build alerts to #kafka-warn.
=> Updating slack channel for Jenkins build alerts

kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestApplication.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/TopicPartitionOffsetResponse.java, kafka-rest/src/main/java/io/confluent/kafkarest/extension/InstantConverterProvider.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/PartitionsResource.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v2/PartitionsResource.java, kafka-rest/src/main/java/io/confluent/kafkarest/v2/KafkaConsumerManager.java, kafka-rest/src/main/java/io/confluent/kafkarest/v2/KafkaConsumerState.java, kafka-rest/src/test/java/io/confluent/kafkarest/unit/PartitionsResourceAbstractConsumeTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/unit/PartitionsResourceAvroProduceTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/unit/PartitionsResourceBinaryProduceTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/unit/PartitionsResourceConsumeTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/unit/PartitionsResourceTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/v2/KafkaConsumerManagerTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/v2/MockConsumer.java, kafka-rest/src/test/java/io/confluent/kafkarest/v2/PartitionsResourceTest.java
CPKAFKA-1526: Extend the topic partition resource to support getting
offset information. The equivalent Java APIs are KafkaConsumer
beginningOffsets, endOffsets and offsetForTimes.
The kafka-rest server will create a randomly generated consumer-group
and consumer to use to query the offsets information. It is possible for
an adversarial user to kill this consumer manually. There are some
measures in place for self-healing if that happens.
=> Add API to get beginning offset, end offset and offset for time.

kafka-rest-common/pom.xml
The rest of the platform was recently upgraded to 1.9.1; this is the equivalent change for kafka-rest.
=> MINOR: Upgade Avro to 1.9.1

kafka-rest-common/pom.xml, kafka-rest-common/src/main/java/io/confluent/kafkarest/KafkaRestConfig.java, kafka-rest-common/src/test/java/io/confluent/kafkarest/KafkaRestConfigTest.java, kafka-rest-scala-consumer/src/main/java/io/confluent/kafkarest/AvroConsumerState.java, kafka-rest-scala-consumer/src/main/java/io/confluent/kafkarest/SimpleConsumerManager.java, kafka-rest/src/main/java/io/confluent/kafkarest/v2/AvroKafkaConsumerState.java
Properties for the Avro Producer were being propagated by accident. Unfortunately (or fortunately, depending on your philosophical stance), this accident didn't happen for the Avro Consumer. This fix explicitly propagate the properties for both.
=> CLIENTS-1454: Propagate Schema Registry properties to KafkaAvroDecoder.

kafka-rest-scala-consumer/pom.xml
Broken after https://github.com/confluentinc/schema-registry/pull/1295.
=> Fix kafka-rest build to use new schema-registry packages.

kafka-rest/src/main/java/io/confluent/kafkarest/RestConfigUtils.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/ClusterTestHarness.java
This fixes a compile error that was created when [KIP-515 Enable ZK client to use the new TLS supported authentication](https://cwiki.apache.org/confluence/display/KAFKA/KIP-515%3A+Enable+ZK+client+to+use+the+new+TLS+supported+authentication) changed the name of a method that was not part of the public Kafka clients API.
This PR does not address the fact that REST Proxy will be unable to connect to a TLS-enabled ZooKeeper instance -- that will have to be fixed separately.
=> Fix compile error due to KIP-515 (ZK TLS)

kafka-rest/src/main/java/io/confluent/kafkarest/backends/kafka/KafkaModule.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/KafkaRestStartUpIntegrationTest.java
The request-scope is needed because the Admin creation logic uses request-scoped auth information. KafkaRestContext itself is a proxied instance, so the result will be cached there appropriately, after it is created.
=> CPKAFKA-4617: Change Admin binding to be request-scoped.

kafka-rest-common/src/main/java/io/confluent/kafkarest/entities/Partition.java, kafka-rest-scala-consumer/src/main/java/io/confluent/kafkarest/MetadataObserver.java, kafka-rest/src/main/java/io/confluent/kafkarest/AdminClientWrapper.java, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/ControllersModule.java, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/PartitionManager.java, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/PartitionManagerImpl.java, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/TopicManagerImpl.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/v1/GetPartitionResponse.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/v2/GetPartitionResponse.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/GetPartitionResponse.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/ListPartitionsResponse.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/ListTopicsResponse.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/PartitionData.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/PartitionsResource.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/V3ResourcesFeature.java, kafka-rest/src/test/java/io/confluent/kafkarest/CompletableFutures.java, kafka-rest/src/test/java/io/confluent/kafkarest/controllers/PartitionManagerImplTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/controllers/TopicManagerImplTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/MetadataAPITest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/PartitionsResourceIntegrationTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v1/PartitionsResourceTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v1/TopicsResourceTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v2/TopicsResourceTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/BrokersResourceTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/ClustersResourceTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/PartitionsResourceTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/TopicsResourceTest.java, testing/environments/minimal/docker-compose.yml
This PR adds endpoints to list and get partitions:
/v3/clusters/{clusterId}/topics/{topicName}/partitions
/v3/clusters/{clusterId}/topics/{topicName}/partitions/{partitionId}
A non-inclusion was (beginning|end)_(offset|timestamp). Somehow, Admin.listOffsets does not seem to be working as I would expect. It always returns beginning_offset as 0 (regardless of the partition being empty or not), and all timestamps are (EPOCH - 1ms). We can add this information later.
=> CLIENTS-1499: Add LIST/GET Partitions V3 endpoints.

kafka-rest/src/main/java/io/confluent/kafkarest/controllers/ControllersModule.java, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/PartitionManagerImpl.java, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/TopicConfigurationManager.java, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/TopicConfigurationManagerImpl.java, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/TopicManager.java, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/TopicManagerImpl.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/Topic.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/TopicConfiguration.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/CreateTopicRequest.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/GetTopicConfigurationResponse.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/ListTopicConfigurationsResponse.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/TopicConfigurationData.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/UpdateTopicConfigurationRequest.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/TopicConfigurationsResource.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/TopicsResource.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/V3ResourcesFeature.java, kafka-rest/src/test/java/io/confluent/kafkarest/controllers/PartitionManagerImplTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/controllers/TopicConfigurationManagerImplTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/controllers/TopicManagerImplTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/TopicConfigurationsResourceIntegrationTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/TopicsResourceIntegrationTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/TopicConfigurationsResourceTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/TopicsResourceTest.java
* CLIENTS-1502: Add LIST/GET Topic Configurations
* CLIENTS-1507: Add UPDATE Topic Configurations
* CLIENTS-1508: Add DELETE Topic Configurations
This PR adds endpoints to LIST/GET/UPDATE/RESET Topic Configurations:
* LIST:   GET    /v3/clusters/{clusterId}/topics/{topicName}/configurations
* GET:    GET    /v3/clusters/{clusterId}/topics/{topicName}/configurations/{name}
* UPDATE: PUT    /v3/clusters/{clusterId}/topics/{topicName}/configurations/{name} --data { "data": { "attributes": { "value": "new_value" } } }
* RESET:  DELETE /v3/clusters/{clusterId}/topics/{topicName}/configurations/{name}
It also adds the ability to specify topic configurations when creating a new topic.
* CREATE: POST /v3/clusters/{clusterId}/topics --data { "data": { "attributes": { "topic_name": "foobar", …
=> Add LIST/GET/UPDATE/RESET Topic Configurations.

kafka-rest/src/main/java/io/confluent/kafkarest/controllers/TopicConfigurationManagerImpl.java, kafka-rest/src/test/java/io/confluent/kafkarest/controllers/TopicConfigurationManagerImplTest.java
The Kafka server will return UnknownTopicOrPartition in case the Topic does not exist, so there's no need to describe the Topic to check for its existence. This change should speed-up the Topic Configuration operations.
=> CLIENTS-1521: Remove GET Topic from LIST/GET/UPDATE/REST Topic Configuration.

kafka-rest/src/test/java/io/confluent/kafkarest/integration/KafkaRestStartUpIntegrationTest.java
This PR is an extra verification testing after a new feature, which customizes HTTP response headers, added to rest-utils due to Kafka REST application based on rest-utils.
confluentinc/rest-utils#177
https://confluentinc.atlassian.net/wiki/spaces/CONNECT/pages/1047197302/One+Pager+-+Customize+HTTP+Response+Headers+on+Kafka+Connect+REST+and+CP+REST+Applications
=> SEC-929--Added one testing for verifying a feature addd to rest-utils repo.

kafka-rest-common/src/main/java/io/confluent/kafkarest/SystemTime.java, kafka-rest-common/src/main/java/io/confluent/kafkarest/Time.java, kafka-rest/src/test/java/io/confluent/kafkarest/mock/MockTime.java, kafka-rest/src/test/java/io/confluent/kafkarest/v2/LoadTest.java
Jira: https://confluentinc.atlassian.net/browse/MMA-7237
**Why**
As part of the efforts to converge on a single telemetry pipelines for Cloud, Hosted Monitoring, and Proactive Support, we want to standardize on one metrics library and associated metrics collection framework.
NOTE: The change here is necessary once https://github.com/confluentinc/rest-utils/pull/178 is merged.
=> Migrate to use AK library instead of common-metrics

kafka-rest/src/main/java/io/confluent/kafkarest/resources/v2/PartitionsResource.java
The Producer will throw an exception if the topic/partition does not exist, and the exception is mapped.
Having the produce-to-topic use the AdminClient actually breaks confluent-security-plugins. This is a short-term solution.
=> Remove spurious topic/partitions existence test when producing.

kafka-rest/src/main/java/io/confluent/kafkarest/resources/v2/ConsumersResource.java
The V1, and intended V2, behaviour was to default to BINARY. Unfortunately V2 uses the same weight for all types, which makes the server choose any of them. Sometimes it chooses the wrong one (thus the flakiness in the build).
=> Fix default Content-Type, when none or any (*/*) is provided.

kafka-rest/src/main/java/io/confluent/kafkarest/controllers/BrokerConfigManager.java, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/BrokerConfigManagerImpl.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/BrokerConfigsResource.java, kafka-rest/src/test/java/io/confluent/kafkarest/controllers/BrokerConfigManagerImplTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/BrokerConfigsResourceIntegrationTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/TopicConfigsResourceIntegrationTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/BrokerConfigResourceTest.java
Add delete endpoint for broker configs.
1. Added unit tests for manager and resource classes.
2. Added integration tests.
Jira - https://confluentinc.atlassian.net/browse/CLIENTS-1505
=> CLIENTS-1505: Add broker config delete endpoint

kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestApplication.java, kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestConfig.java, kafka-rest/src/test/java/io/confluent/kafkarest/KafkaRestConfigTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/unit/UriUtilsTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/v2/KafkaConsumerManagerTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/v2/PartitionsResourceTest.java
All KafkaRestConfig constructors throw RestConfigException despite this exception only being thrown in `public KafkaRestConfig(String propsFile)`. This makes for an undesirable developer experience.
=> Remove RestConfigException from constructor signatures

kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestApplication.java
The original constructor fails to set restResourceExtensions causing an NPE when setting up resources.
=> Fix KafkaRestApplication(Properties) constructor

kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestApplication.java, kafka-rest/src/main/java/io/confluent/kafkarest/backends/BackendsModule.java, kafka-rest/src/main/java/io/confluent/kafkarest/backends/kafka/KafkaModule.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v2/BrokersResource.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v2/PartitionsResource.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v2/TopicsResource.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/BrokerConfigsResource.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/BrokersResource.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/ClustersResource.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/PartitionsResource.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/ReplicasResource.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/SearchReplicasByBrokerAction.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/TopicConfigsResource.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/TopicsResource.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v2/BrokersResourceTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v2/TopicsResourceTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/BrokerConfigResourceTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/BrokersResourceTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/ClustersResourceTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/PartitionsResourceTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/ReplicasResourceTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/SearchReplicasByBrokerActionTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/TopicConfigsResourceTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/TopicsResourceTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/v2/PartitionsResourceTest.java
Background: Confluent security plugins for REST Proxy perform authentication in a Post-Match Filter. Upon successful authentication, it sets up AdminClient connection accordingly. Later on, we bind Admin to this AdminClient instance created during authentication, and this instance is what is injected in the controllers/resources.
The problem: JSR 339/JAX-RS 2.0 specification, Section 3.7.2, Step 3 [1], specifies that the resource instance must be created in the Resource Match phase, which happens before the Post-Match Filter phase (see Appendix C). Therefore, at the time the Admin is injected in the resources, AdminClient has not been properly set yet. A default unauthenticated instance is injected instead.
The solution: A possible solution would be to move the authentication to the …
=> Fix REST Proxy injection-based authentication.

kafka-rest/src/main/java/io/confluent/kafkarest/controllers/BrokerConfigManagerImpl.java, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/TopicConfigManagerImpl.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/AbstractConfig.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/BrokerConfig.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/ConfigSource.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/ConfigSynonym.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/TopicConfig.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/BrokerConfigData.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/ConfigSynonymData.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/TopicConfigData.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/BrokerConfigsResource.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/TopicConfigsResource.java, kafka-rest/src/test/java/io/confluent/kafkarest/controllers/BrokerConfigManagerImplTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/controllers/TopicConfigManagerImplTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/BrokerConfigsResourceIntegrationTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/TopicConfigsResourceIntegrationTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/TopicsResourceIntegrationTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v2/TopicsResourceTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/BrokerConfigResourceTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/TopicConfigsResourceTest.java
This PR adds two fields to broker and topic configs:
Source:
```
"source": "DYNAMIC_TOPIC_CONFIG"
```
Synonyms:
```
"synonyms": [
{
"name": "min.insync.replicas",
"value": "2",
"source": "DYNAMIC_TOPIC_CONFIG"
},
{
"name": "min.insync.replicas",
"value": "1",
"source": "DEFAULT_CONFIG"
}
]
```
=> KIP-226: Add support for configs source and synonyms.

kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestApplication.java, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/AbstractConfigManager.java, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/BrokerConfigManagerImpl.java, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/ClusterConfigManager.java, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/ClusterConfigManagerImpl.java, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/ControllersModule.java, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/TopicConfigManagerImpl.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/AbstractConfig.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/BrokerConfig.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/ClusterConfig.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/ClusterConfigData.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/GetClusterConfigResponse.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/ListClusterConfigsResponse.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/UpdateClusterConfigRequest.java, kafka-rest/src/main/java/io/confluent/kafkarest/extension/ClusterConfigTypeConverterProvider.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/ClusterConfigsResource.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/V3ResourcesFeature.java, kafka-rest/src/test/java/io/confluent/kafkarest/controllers/ClusterConfigManagerImplTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/ClusterConfigsResourceIntegrationTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/ClusterConfigResourceTest.java
This PR adds 8 new endpoints:
* List current cluster-wide dynamic default configs:
Request:
```
GET /v3/clusters/{clusterId}/broker-configs
and
GET /v3/clusters/{clusterId}/topic-configs
```
Example response (note only the dynamic default configs are returned, instead of all configs):
```
HTTP 200 OK
{
"links": {
"self": "http://localhost:9391/v3/clusters/60huKN8RTdW40AAchhHJIw/broker-configs",
"next": null
},
"data": [
{
"id": "crn:///kafka=60huKN8RTdW40AAchhHJIw/broker-config=compression.type",
"links": {
"self": "http://localhost:9391/v3/clusters/60huKN8RTdW40AAchhHJIw/broker-configs/compression.type"
},
"attributes": {
"cluster_id": "60huKN8RTdW40AAchhHJIw",
"config_type": "BROKER",
"name": "compression.type",
"value": "gzip",
"is_default": false,
"is_read_only": false, …
```
=> KIP-226: Add cluster-wide dynamic default configs.

kafka-rest/src/main/java/io/confluent/kafkarest/controllers/AbstractConfigManager.java, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/BrokerConfigManager.java, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/BrokerConfigManagerImpl.java, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/ClusterConfigManager.java, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/ClusterConfigManagerImpl.java, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/TopicConfigManager.java, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/TopicConfigManagerImpl.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/AlterConfigCommand.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/AlterBrokerConfigBatchRequest.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/AlterClusterConfigBatchRequest.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/AlterConfigBatchRequestData.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/AlterTopicConfigBatchRequest.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/AlterBrokerConfigBatchAction.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/AlterClusterConfigBatchAction.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/AlterTopicConfigBatchAction.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/V3ResourcesFeature.java, kafka-rest/src/test/java/io/confluent/kafkarest/controllers/BrokerConfigManagerImplTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/controllers/ClusterConfigManagerImplTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/controllers/TopicConfigManagerImplTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/BrokerConfigsResourceIntegrationTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/ClusterConfigsResourceIntegrationTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/TopicConfigsResourceIntegrationTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/AlterBrokerConfigBatchActionTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/AlterClusterConfigBatchActionTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/AlterTopicConfigBatchActionTest.java
New APIs:
* `POST /v3/clusters/{clusterId}/broker-configs:alter`
* `POST /v3/clusters/{clusterId}/topic-configs:alter`
* `POST /v3/clusters/{clusterId}/brokers/{brokerId}/configs:alter`
* `POST /v3/clusters/{clusterId}/topics/{topicName}/configs:alter`
Request body:
```
{
"data": [
{
"name": "compression.type",
"value": "gzip",
"operation": "UPDATE"
},
{
"name": "max.connections",
"operation": "DELETE"
}
]
}
```
`operation` can be `UPDATE` and `DELETE`. It's optional and defaults to `UPDATE` if not specified. `value` defaults to `null` and is ignored if `operation` is `DELETE`.
HTTP 204 No Content is returned on success. The update is atomic: either the whole batch succeeds or fails.
=> Add Batch Alter (UPDATE/DELETE) Broker/Cluster/Topic configs.

checkstyle/suppressions.xml, kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/ClusterData.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/PartitionData.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/TopicData.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/ClustersResource.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/ListAllReassignmentsAction.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/PartitionsResource.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/SearchReassignmentsByTopicAction.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/TopicsResource.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/ClustersResourceIntegrationTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/GetReassignmentActionIntegrationTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/ListAllReassignmentsActionIntegrationTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/PartitionsResourceIntegrationTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/SearchReassignmentsByTopicActionIntegrationTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/TopicsResourceIntegrationTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/ClustersResourceTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/PartitionsResourceTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/TopicsResourceTest.java
- Added relationship for reassignment to cluster, topic and partition.
- Refactor `reassignments` to `reassignment` since it is indeed a resource not a collection.
Modified unit and integration tests.
Tested locally with `mvn test`
=> CLIENTS-1597: Add relationship reassignment and refactor reassignment resource

kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestApplication.java
What: KafkaHttpServlet was an abstraction created when we intended to write applications for the Kafka HTTP server inside the ce-kafka repository. Since that's not the case anymore, this abstraction is no longer needed.
Why: KafkaHttpServlet wraps rest-utils Application, only exposing the minimum necessary from Application's extensive public API. Whenever we need something extra, we have to first expose it. It turns out that to be able to enable the Telemetry Reporter for (Embedded) REST Proxy, we need to make extensive non-trivial modifications to KafkaHttpServlet. All this is work is not needed if we just don't wrap application anymore.
=> CLIENTS-1599: Add constructor accepting path to KafkaRestApplication.

kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestConfig.java, kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestMetricsContext.java, kafka-rest/src/test/java/io/confluent/kafkarest/KafkaRestConfigTest.java
This is not explicitly added to the config def as its not intended to actually be set manually by users at this time.
=> Enable setting cluster_id on KafkaRestMetricsContext

kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestMetricsContext.java
Wrong resource label was used to identify the kafka cluster id.
=> Change resource label resource.kafka.cluster.id to resource.cluster.id

kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestApplication.java, kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestConfig.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/ResourcesFeature.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v2/DisableV2Test.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/DisableV3Test.java
The configurations are, respectively, `api.v2.enable` and `api.v3.enable`. Both default to true.
=> CLIENTS-1613: Add configuration to enable/disable V2 and V3 APIs.

kafka-rest/pom.xml
- Confluent repackaged version fixes CVE-2019-17571
- `common/pom.xml` excludes default log4j as a transitive dependency, and the repackaged version must be explicitly added.
Ref: https://github.com/confluentinc/common/pull/270
=> SEC-1034: log4j migration to confluent repackaged version

kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestConfig.java, kafka-rest/src/test/java/io/confluent/kafkarest/KafkaRestConfigTest.java
What: Move helper function and prefix to parent class. 
Why: Currently rest-utils passes all originals to the metrics reporter. KafkaRest only passes metrics configuration properties prefixed with `metric.reporters.`  We need them to handle this consistently to ensure users don't have to configure it twice. Once for rest utils and another for KafkaRest clients. Likewise we can't adopt the strategy of passing all config values to managed clients so we rely on the prefix. The prefix strategy is more in line with existing config namespacing (consumer., client., producer.) so this is the approach we moved to rest-utils. 
rest-utils pr: https://github.com/confluentinc/rest-utils/pull/190
=> Move MetricsReporter Config extraction to  rest-utils

kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestConfig.java, kafka-rest/src/test/java/io/confluent/kafkarest/KafkaRestConfigTest.java
KafkaRest managed clients should inherit the KafkaRestApplication's metrics reporter configs when not configured as a client override. 
There is a new metrics reporter, ConfluentTelemetryReporter, who's configurations need to be propagated as well. 
This PR addresses both concerns.
=> Propagate Confluent Telemetry Reporter configuration properties to managed clients.

kafka-rest/src/main/java/io/confluent/kafkarest/tools/ConsumerPerformance.java, kafka-rest/src/main/java/io/confluent/kafkarest/tools/ProducerPerformance.java
The following two files were removed as part of the v1 removal. They are however still required by existing system tests. 
Removal:
https://github.com/confluentinc/kafka-rest/pull/647/files
=> Add [Consumer|Producer]Performance tools back

bin/kafka-rest-run-class
Add `share/java/confluent-telemetry` to kafka-rest's classpath.
This is where we'll install the confluent-metrics jar (as part of packaging) and we need this jar for telemetry to work.
=> METRICS-1988: add confluent-telemetry directory to kafka-rest-run-class

kafka-rest/pom.xml, pom.xml
Also uses `${jackson.version}` for `jackson-datatype-*`.
=> CLIENTS-1657: Explicitly depend on Guava.

kafka-rest/pom.xml
This pull request cherry-picks a commit from `master` to add explicit `io.confluent:confluent-log4j` dependency, because we blacklist the (vulnerable) tranistive dependency `log4j:log4j` of `org.slf4j:slf4j-log4j12` explicitly in `common`. `io.confluent:confluent-log4j` is a drop-in replacement of `log4j:log4j` with a fix for the vulnerability.
=> SEC-1307: Backport "log4j replacement with confluent repackaged version"

kafka-rest/pom.xml, kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestApplication.java, kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestConfig.java, kafka-rest/src/main/java/io/confluent/kafkarest/RestConfigUtils.java
We should only depend on the kafka-clients jar.
=> CLIENTS-1659: Remove V1 API Kafka core dependency and associated Zookeeper Client configs

kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/AclsResource.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/AlterBrokerConfigBatchAction.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/AlterClusterConfigBatchAction.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/AlterTopicConfigBatchAction.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/BrokerConfigsResource.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/BrokersResource.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/ClusterConfigsResource.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/ClustersResource.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/ConsumerAssignmentsResource.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/ConsumerGroupsResource.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/ConsumersResource.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/GetReassignmentAction.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/ListAllReassignmentsAction.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/PartitionsResource.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/ReplicasResource.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/SearchReassignmentsByTopicAction.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/SearchReplicasByBrokerAction.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/TopicConfigsResource.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/TopicsResource.java, testing/environments/minimal/docker-compose.yml
Tested using VisualVM.
Prefixes:
```
v3.clusters.list.
v3.clusters.get.
v3.acls.list.
v3.acls.create.
v3.acls.delete.
v3.clusters.configs.list.
v3.clusters.configs.alter.
v3.clusters.configs.get.
v3.clusters.configs.update.
v3.clusters.configs.delete.
v3.brokers.list.
v3.brokers.get.
v3.brokers.configs.list.
v3.brokers.configs.alter.
v3.brokers.configs.get.
v3.brokers.configs.update.
v3.brokers.configs.delete.
v3.brokers.partition-replicas.list.
v3.consumer-groups.list.
v3.consumer-gropus.get.
v3.consumers.list.
v3.consumers.get.
v3.consumer-assignments.list.
v3.consumer-assignments.get.
v3.topics.list.
v3.topics.create.
v3.topics.get.
v3.topics.delete.
v3.topics.configs.list.
v3.topics.configs.alter.
v3.topics.configs.get.
v3.topics.configs.update.
v3.topics.configs.delete. …
```
=> KREST-5: Add JMX metrics for all V3 endpoints.

kafka-rest/src/main/java/io/confluent/kafkarest/response/UrlFactoryImpl.java, kafka-rest/src/test/java/io/confluent/kafkarest/response/UrlFactoryImplTest.java
For V3 APIs, the preference order for returned URLs should be:
1. advertised.listeners config
2. listeners config
3. host.name and port config
4. request base URL
Currently the order is (3, 1, 2, 4). Reorder them to the correct order.
=> KREST-7: Make advertised.listeners and listeners precede host.name:port.

Jenkinsfile, debian/Makefile, kafka-rest-console-scripts/pom.xml, kafka-rest/pom.xml, pom.xml
Setting the jenkins config to use nano versioning. No longer need to define upstream repos as we now define downstream repos which will be automated in the future. Removed all of the snapshot versions and replaced with nano versions. Updated all of the dependency versions. Updated the make file so the rpm version parsing works with nano versioning, and applied the batch mode option to all maven commands so we don't get download progress and color codes in the CI logs.
These changes will be merged during phase two of the nano versioning roll out.
=> ST-3461: Nano versioning

kafka-rest/src/main/java/io/confluent/kafkarest/v2/KafkaConsumerReadTask.java, kafka-rest/src/main/java/io/confluent/kafkarest/v2/KafkaConsumerState.java
Concurrent consume requests on the same consumer could race in between calls to `KafkaConsumerState.hasNext()` and `KafkaConsumerState.next()`. I use double-checked locking in `KafkaConsumerReadTask` to allow multiple consume requests on the same consumer to make progress in parallel (instead of one request completing at a time, per consumer).
=> KREST-182: (Correctly) fences access to internal consumer buffer.

kafka-rest/src/main/java/io/confluent/kafkarest/controllers/TopicManager.java, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/TopicManagerImpl.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/CreateTopicRequest.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/TopicsResource.java, kafka-rest/src/test/java/io/confluent/kafkarest/controllers/TopicManagerImplTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/TopicsResourceIntegrationTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/TopicsResourceTest.java
They default to `num.partitions` and `default.replication.factor` broker configs, respectively.
=> KREST-155: Make partitions_count and replication_factor optional in Create Topic V3 API.

kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestConfig.java, kafka-rest/src/main/java/io/confluent/kafkarest/UriUtils.java, kafka-rest/src/main/java/io/confluent/kafkarest/config/ConfigModule.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v2/ConsumersResource.java, kafka-rest/src/main/java/io/confluent/kafkarest/response/UrlFactoryImpl.java, kafka-rest/src/test/java/io/confluent/kafkarest/response/UrlFactoryImplTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/unit/UriUtilsTest.java
Config advertised.listeners was added in 6.0.0 to specify which base path to use when generation absolute URLs in V3 API responses. Consume V2 API has a similar mechanism, that uses the host.name and port configs. This PR unifies both mechanisms, so that the URLs generated in both V2 and V3 are based on the same base path.
=> KREST-147: Make absolute URL generation consistent in V2 and V3.

kafka-rest/src/main/java/io/confluent/kafkarest/response/UrlFactoryImpl.java, kafka-rest/src/test/java/io/confluent/kafkarest/response/UrlFactoryImplTest.java
https://github.com/confluentinc/kafka-rest/pull/768 introduced a regression in V2 absolute URL generation, whereas before listeners was never used for generation, and now it takes precedence over request URI. This PR fixes the regression by never using listeners for URL generation (both for V2 and V3 APIs). Request URI is always a better guess then listeners, and people should be able to override it using advertised.listeners or host.name and port as before.
=> KREST-200: Never user listeners for URL generation in V2 and V3.

kafka-rest/src/main/java/io/confluent/kafkarest/extension/EnumConverterProvider.java, kafka-rest/src/test/java/io/confluent/kafkarest/extension/EnumConverterProviderTest.java
Jackson has a nice feature which allows it to parse JSON values as enums based on a method annotated in the enum class with `@JsonValue`. Currently we only support parsing enums from path params via name (case-insensitive) matching. This PR extends the parsing logic to also parse based on `@JsonValue` annotated method, if one is available in the class.
=> Allow translation of enum path params based on @JsonValue.

kafka-rest/src/main/java/io/confluent/kafkarest/DefaultKafkaRestContext.java, kafka-rest/src/test/java/io/confluent/kafkarest/unit/DefaultKafkaRestContextTest.java
It is possible for multiple requests to arrive prior to resource initialization which can result in a multiple pools being created/leaked. This PR intends to synchronize the process of obtaining these resources to avoid such a situation.
=> KREST-287: Syncronize resource pools/managers lazy instantiation.

kafka-rest/src/test/java/io/confluent/kafkarest/integration/ClusterTestHarness.java
The integration tests in kafka rest use ClusterTestHarness that has set up to bring up the services. This PR concerns modifying the way kafka servers are set up. Currently, the brokers are started sequentially which is a drawback to have topics with replication_factor > 1. This PR works on concurrently starting brokers.
Making sure all tests pass.
Jira - https://confluentinc.atlassian.net/browse/KREST-360
=> KREST-360: Start brokers concurrently in ClusterTestHarness

api/v3/openapi.yaml, checkstyle/suppressions.xml, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/TopicManager.java, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/TopicManagerImpl.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/CreateTopicRequest.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/TopicsResource.java, kafka-rest/src/test/java/io/confluent/kafkarest/controllers/TopicManagerImplTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/TopicsResourceIntegrationTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/TopicsResourceTest.java
This change adds the ability to create a topic with a custom, explicitly specified mapping of partition to broker replicas.
The approach taken is the path of least resistance - adding yet another parameter to the `TopicManager` topic creation API, and not that far from the approach taken in the Kafka Admin client where the `NewTopic` spec contains both a field for such mappings, and fields for number of partitions and replication factor.
- Alternatively we could have introduced a DTO/spec object acting akin to `NewTopic` in the Kafka Admin client. This would have kept the `TopicManager` API more stable, but it would have added yet another class representing some form of a topic (alongside `CreateTopicRequest`, `Topic`, `TopicData`, `NewTopic`).  Having in mind that `TopicManager` is an …
=> KREST-456 Add API for creating a topic with custom partition-to-replicas assignments

kafka-rest/src/test/java/io/confluent/kafkarest/integration/AbstractProducerTest.java
This enables correctly running some tests in `confluent-security-plugins/confluent-kafka-rest-security-plugin` (PR to follow soon).
_Nota bene_: I'd like to avoid keeping the possibly redundant `(String, TopicRequestT, Map<String, String>)` overload, so hopefully the PR CI will check and notify me if a downstream dependency breaks due to that overload's removal. If CI is green, I'll add reviewers for this PR.
=> Allow setting the request contentType in testProduceToAuthorizationError

kafka-rest/src/test/java/io/confluent/kafkarest/unit/DefaultKafkaRestContextTest.java
Tested locally in IntelliJ IDEA and via the command line.
With both approaches the results were fairly consistent, and out of 100 runs of `DefaultKafkaRestContextTest` (so a total of 300 tests):
- **before** the change, there were consistently between 5 and 10 failures.
- **after** the change, there were consistently no failures.
=> KREST-524 Fix a test failure caused by a HashSet used concurrently.

kafka-rest/src/test/java/io/confluent/kafkarest/TestUtils.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/TopicsResourceIntegrationTest.java
Adds a simple test retry utility that should help with inherently racy test procedures that nevertheless are expected to pass if given a little bit of slack.
One example of a procedure like that is topic creation/deletion immediately followed by checking for the topic's presence/absence in the list of available topics.
- To me this sounded like a pretty bad case of not reading your own writes, but apparently this is a known issue related to reading from different data sources (broker vs ZK).
Before this change, when running locally on my machine, the flaky tests causing [KREST-491](https://confluentinc.atlassian.net/browse/KREST-491) and [KREST-496](https://confluentinc.atlassian.net/browse/KREST-496) were failing ~30 times out of 200 total test runs. After this change, they were failing …
=> KREST-491 Test with exponential backoff retries racy checks causing flaky failures in TopicsResourceIntegrationTest

kafka-rest/src/test/java/io/confluent/kafkarest/TestUtils.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/BrokerConfigsResourceIntegrationTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/ClusterConfigsResourceIntegrationTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/TopicConfigsResourceIntegrationTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/TopicsResourceIntegrationTest.java
All of the tests below are flaky due to lack of consistency for admin operations in Kafka.
Test failures addressed:
* https://confluentinc.atlassian.net/browse/KREST-522
* https://confluentinc.atlassian.net/browse/KREST-527
* https://confluentinc.atlassian.net/browse/KREST-542
* https://confluentinc.atlassian.net/browse/KREST-546
* https://confluentinc.atlassian.net/browse/KREST-547
* https://confluentinc.atlassian.net/browse/KREST-555
=> KREST-561: Add retries for flaky tests.

kafka-rest/src/test/java/io/confluent/kafkarest/unit/DefaultKafkaRestContextTest.java
As the changes causing the [KREST-524](https://confluentinc.atlassian.net/browse/KREST-524)/[KREST-558](https://confluentinc.atlassian.net/browse/KREST-558) failures originally landed in `5.5.x`, the corresponding fix should have been merged starting from there.
This change cherry-picks it in `5.5.x` - it also needs to be merged up from there to `6.0.x`.
- From `6.0.x` though it's probably best to just `-s ours` merge up to `6.1.x` and `master`.
Tested locally in IntelliJ IDEA, by running 100 runs of `DefaultKafkaRestContextTest` (so a total of 400 tests):
- **before** the change, there were consistently between 5 and 10 failures.
- **after** the change, there were consistently no failures.
=> KREST-558 Backport the fix for KREST-524 (fixing a concurrent test failure) to 5.5.x and 6.0.x.

kafka-rest/src/test/java/io/confluent/kafkarest/unit/DefaultKafkaRestContextTest.java
See #799 - this is a manual merge of the `5.5.x` fix from there into a `6.0.x`-based branch.
Created explicitly (and not `pint merge`-d) because the simple merge hits conflicts.
Tested locally in IntelliJ IDEA, by running 100 runs of `DefaultKafkaRestContextTest` (so a total of 300 tests):
- **before** the change, there were consistently between 5 and 10 failures.
- **after** the change, there were consistently no failures.
=> KREST-558 6.0.x

api/v3/openapi.yaml, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/ConsumerGroupLagSummaryManager.java, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/ConsumerGroupLagSummaryManagerImpl.java, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/ControllersModule.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/ConsumerGroupLagSummary.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/ConsumerGroupData.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/ConsumerGroupLagSummaryData.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/GetConsumerGroupLagSummaryResponse.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/ConsumerGroupLagSummariesResource.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/ConsumerGroupsResource.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/V3ResourcesFeature.java, kafka-rest/src/test/java/io/confluent/kafkarest/controllers/ConsumerGroupLagSummaryManagerImplTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/ConsumerGroupLagSummariesResourceIntegrationTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/ConsumerGroupsResourceIntegrationTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/ConsumerGroupLagSummariesResourceTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/ConsumerGroupsResourceTest.java
The name `ConsumerGroupLag` isn't too clear, especially when we also have `ConsumerLag`
Regenerating kafka-rest-sdk-go further illustrates the vagueness - https://github.com/confluentinc/kafka-rest-sdk-go/pull/5#discussion_r573758885
Also realized during refactoring that openapi.yaml was missing `lag_summary` links for ConsumerGroup
=> Renaming consumer group lag to consumer group lag summary for clarity

README.md, bin/kafka-rest-run-class, kafka-rest/pom.xml, kafka-rest/src/assembly/package.xml
Fixes the `kafka-rest-run-class` script to correctly work with the `development` assembly target, moves the `standalone` assembly target into the main profile, and beefs up a bit the Deployment section of the README.
Tested by ensuring that after a `mvn clean package`:
- the `kafka-rest-start` script now can be used to deploy the local changes.
- We still need to pass valid configuration. I didn't default to the `./config/kafka-rest.properties` ones to avoid side effects to the `package` use-cases.
- ` java -jar ./kafka-rest/target/kafka-rest-6.2.0.0-standalone.jar ./config/kafka-rest.properties` correctly starts a server with the local changes if `kafka-rest.properties` is valid.
=> KREST-638 Some small deployment improvements.

api/v3/openapi.yaml
Add missing example for `CreateAclRequest` schema.
Docs has `CreateAclRequest` with field `resource_name` missing and values set to `UNKNOWN` that looks like - 
{
"resource_type": "UNKNOWN",
"pattern_type": "UNKNOWN",
"principal": "string",
"host": "string",
"operation": "UNKNOWN",
"permission": "UNKNOWN"
}
Docs link - https://docs.confluent.io/platform/current/kafka-rest/api.html#post--clusters-cluster_id-acls
Validated api spec with - 
`swagger-cli validate api/v3/openapi.yaml `
`openapi-examples-validator api/v3/openapi.yaml`
`npx redoc-cli serve api/v3/openapi.yaml`
Jira - https://confluentinc.atlassian.net/browse/KREST-117
=> KREST-117: Add missing example for create acl

kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/ConsumerLagsResourceIntegrationTest.java
Wrapping consumer subscribes and polls in retry block to remove flakiness and address the following test failures
https://confluentinc.atlassian.net/browse/KREST-625?atlOrigin=eyJpIjoiMzVjMzg2Njc5MDQxNDUzYWI2NjVjMWY1YzRhYmJjNmMiLCJwIjoiaiJ9
https://confluentinc.atlassian.net/browse/KREST-616?atlOrigin=eyJpIjoiOGJkYTcxNjZmMjFjNGNkOThhZTM0ZDgxMTBhMTk4ZGIiLCJwIjoiaiJ9
=> Adding retries to ConsumerLagsResourceIntegrationTest

Jenkinsfile
This change serves to address the issue of noisiness in #rest-proxy-eng which will serve human communication and all machine chatter will move to #rest-proxy-warn.
Slack thread: https://confluent.slack.com/archives/C2MCH5QJE/p1614850839024400
=> Move slack build messages to #rest-proxy-warn.

kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/ProduceAction.java
With:
- `@ResourceName` (so that it can be blocked if needed)
- `@PerformanceMetric` (so that metrics for it are exported)
Tested locally, by making sure that the API can be blocked with `api.endpoints.blocklist`, and that metrics for it are exported as attributes (e.g. `v3.records.create.request-error-rate`) to the `kafka-rest:type=jersey-metrics` MBean.
=> KREST-770 Annotate the v3 Produce API

kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/ProduceAction.java
Due to my last rebase for [the KREST-771 changes](https://github.com/confluentinc/kafka-rest/pull/823) not being recent enough, I have missed to update `ProduceAction` accordingly.
This breaks `kafka-rest`, so this change fixes that breakage.
=> KREST-771 Fix build breakage by also updating ProduceAction.java

kafka-rest/src/test/java/io/confluent/kafkarest/TestUtils.java
Reduce coupling to `kafka-clients` by providing our own `waitForCondition` test utilities based on `testWithRetry`.
=> KREST-826, KREST-837 Reduce coupling to kafka-clients

kafka-rest/src/test/java/io/confluent/kafkarest/integration/AuthorizationErrorTest.java
Starting from `5.4.x`, this will fix the deprecated API usage in `master` that is affected by https://github.com/confluentinc/kafka/pull/544.
- There are other deprecated API usages across the different branches, which should be addressed as soon as possible.
Tested locally with `mvn -f kafka-rest/pom.xml -Dit.test=AuthorizationErrorTest test-compile failsafe:integration-test`.
=> KREST-865 Remove usage of the deprecated SimpleAclAuthorizer.

kafka-rest/src/main/java/io/confluent/kafkarest/entities/ConfigSource.java, kafka-rest/src/test/java/io/confluent/kafkarest/OpenConfigEntry.java, kafka-rest/src/test/java/io/confluent/kafkarest/controllers/BrokerConfigManagerImplTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/controllers/ClusterConfigManagerImplTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/controllers/TopicConfigManagerImplTest.java
That constructor was actually used a lot throughout the configuration management tests.
Because there's no good alternative for that constructor, a subtype mimicking the old constructor was added.
As the deprecated constructor is actually being removed in the most recent AK version, I'll go ahead and merge this once CI looks good. The PR will be available for post-merge reviews and for posterity.
Tested locally, by ensuring that the affected tests still pass, and that IntelliJ doesn't find any other usages of the deprecated constructor.
P.S. Moving away from this constructor also means it's better to change our `AbstractConfig` concept, so that it relies on the config source to determine whether the related config is default or not. That change however affects many classes, so it should …
=> KREST-865 Remove usage of a deprecated Admin Client ConfigEntry constructor

kafka-rest/src/test/java/io/confluent/kafkarest/integration/SecureTestUtils.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/AclsResourceIntegrationTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/testing/KafkaBrokerFixture.java, testing/environments/sasl_plain/docker-compose.yml
There are various test files and utilities that use the deprecated class by having it set as a string property that gets loaded at runtime.
Because of them, the latest CI runs of `kafka-rest` on `master` fail spectacularly with tons of failures.
That problem wasn't visible in the downstream validation of the Kafka PR, where the `kafka-rest` validation seemed to have completed successfully.
- We need to figure out if the downstream validation did run the tests, but the report is just hidden somewhere in the full stage view of the CI job.
Like with #834, I'll go ahead and merge this once CI looks good.
Tested locally by running all tests in IntelliJ (all successful, except the flaky `KafkaConsumerManagerTest.testBackoffMsControlsPollCalls`), and by verifying that the `sasl_plain` …
=> KREST-865 Remove string usages of the class name of the deprecated SimpleAclAuthorizer

kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/ProduceAction.java
There is a subtle bug in `produce` logic where KafkaRestCleanupFilter is called before the lambda function (passed to StreamingResponse) is executed. This has got to do with how jersey handles(or lack of thereof) `ChunkedOutput` during a request's lifecycle. Basically, once `AsyncResponse` is resumed the subsequent Filters are executed. This leads to `KafkaRestContextProvider` getting reset before the `produceController` can be resolved. As a result, the `KafkaRestContext` is not the one that is set by the client but instead is `DefaultKafkaRestContext`.
The fix in this PR is to resolve `produceController` outside of the lambda function.  A better fix, however, would be to 
1. Call `KafkaRestContextProvider.clearCurrentContext()` inside one of the lifecycle event listeners. 
2. If 1. is …
=> fix: resolve ProduceController early/outside of lambda

kafka-rest/src/test/java/io/confluent/kafkarest/v2/KafkaConsumerManagerTest.java
Current way it is being tested, it relies on Thread.sleep to try to peek into the KafkaConsumerManager at right time. Problem is, 1. it is using the wrong time (it assumes the backoff is 250ms, when actually it is 50ms), and 2. it is peeking the wrong thing. I just looks if there's a delayed task, but that gives no guarantees the task is being retried at the given backoff. So I rewrote it to actually the backoff.
It was previously consistently failing 5% of time (out of 1000 runs). Now it fails 0%. :)
Example failure: https://jenkins.confluent.io/job/confluentinc/job/kafka-rest/job/6.0.x/480/testReport/junit/io.confluent.kafkarest.v2/KafkaConsumerManagerTest/testBackoffMsControlsPollCalls/
=> KREST-600: Fix KafkaConsumerManagerTest.testBackoffMsControlsPollCalls flaky test.

api/v3/openapi.yaml, kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/TopicData.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/TopicsResourceTest.java
**What**
Get useful meta info without making an additional call to fetch the full partition data. 
**Why**
For the web clients that show topic data in a single view (e.g. table), making an additional call to get and display partition count leads to an inefficient fetch pattern.
=> MMA-10490: include count of partitions in topic(s) response

kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestConfig.java
Fully testing this (running the system test with the updated `kafka-rest` sources) is quite laborious and finicky, so I'm still in the process of doing that.
- I'm following https://github.com/confluentinc/muckrake/blob/master/ducker/README.md#creating-your-own-ducker-images and have hit and fixed multiple different problems so far.
Still, I was able to check on a local `kafka-rest` instance that with the following added to the config properties:
```
consumer.interceptor.classes=io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor
consumer.confluent.monitoring.interceptor.topic=_confluent-monitoring-ddimitrov-consumer
consumer.confluent.monitoring.interceptor.publishMs=1000
producer.interceptor.classes=io.confluent.monitoring.clients.interceptor.MonitoringProducerInter …
```
=> KREST-481 Fix a problem with configuring monitoring interceptors

kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/TopicsResourceIntegrationTest.java
**What**
Fix the integration test failure. The change here though includes more than just the fix for the test. `TopicManager.createTopic` has been changed to return `CreateTopicsResult` instead of void. Few advantages of doing this
1. Caller can decide how it wants to use `CreateTopicsResult` ([example](https://github.com/confluentinc/kafka-rest/pull/845/files#diff-0811689ae333a0789fa5a6c9911332eeb8fb48ebfac0f0401ff329f4d9b6375fR681)). On the flip side, it is the responsibility of the caller now to make sure create has succeeded. This is not a publicly exposed API so no impact on backward compatibility.
2. Allows us to return the correct partition count vs passing back arbitrary value.
=> fix integration test

kafka-rest/pom.xml, pom.xml
#317 fixed a problem with a missing SLF4J dependency - apparently the problem was related to migrating a lot of the dependency management into `common`. Unfortunately the fix also introduced versioning for the dependency in `kafka-rest` while the same SLF4J dependency was already versioned and managed in `common`.
This change removes that versioning, in order to allow that dependency (which is a sensitive one, as it transitively includes a vulnerable version of Log4J) to be entirely managed in `common`.
The change was tested locally, by ensuring that a clean local build passes.
In addition to that, locally I merged the change up to `master` to see what problems should be expected with `pint merge`. It turns out that the version is added to one other subproject in `5.3.x` (so it has to be …
=> KREST-1029 Remove SLF4J versioning from kafka-rest.

kafka-rest-scala-consumer/pom.xml, kafka-rest/pom.xml, pom.xml
See #851.
This is a follow-up to the KREST-1029 fix which removes an unnecessary SLF4J versioning from `kafka-rest`. Here we also have to remove the version from one other place where it's being used. After #851 is merged (ideally with "Rebase and merge"), and this PR follows it, we should be able to `pint merge` the change up to `6.0.x`, and after a conflict fix there, again up to `master`.
=> KREST-1029 Fix SLF4J versioning in 5.3.x.

kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestConfig.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/JsonParsingErrorTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/SchemaRegistrySaslInheritTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/testing/JvmPropertyFileLoginModuleFixture.java, kafka-rest/src/test/java/io/confluent/kafkarest/testing/KafkaBrokerFixture.java, kafka-rest/src/test/java/io/confluent/kafkarest/testing/KafkaClusterFixture.java, kafka-rest/src/test/java/io/confluent/kafkarest/testing/KafkaRestFixture.java, kafka-rest/src/test/java/io/confluent/kafkarest/testing/SchemaRegistryFixture.java, kafka-rest/src/test/java/io/confluent/kafkarest/testing/ZookeeperFixture.java
Schema Registry client needs `sasl.jaas.config` when `basic.auth.credentials.source=SASL_INHERIT`.
=> KREST-1187: Propagate client.sasl.jaas.config to Schema Registry.

kafka-rest-common/pom.xml
Our `5.3.x` branch peculiarly includes a vulnerable transitive dependency to `jackson-mapper-asl:1.9.13` which is not present in `5.2.x` or `5.4.x`. This dependency comes via a direct dependency to `avro:1.8.2` that we specify in the `kafka-rest-common` module.
- In `5.2.x` there's no `kafka-rest-common` module;
- In `5.4.x` the `avro` dependency has been bumped to `1.9.1`;
This change specifically excludes `jackson-mapper-asl` from `avro` in `kafka-rest-common` on `5.3.x`.
I'm still hesitating whether to merge this upwards to `5.5.x`, as like previously explained `5.4.x` (and `5.5.x`) use newer versions of `avro`, and on `6.0.x` and upwards, there's no `kafka-rest-common` module again.
- On one hand, excluding it will also prevent vulnerabilities from future versions of …
=> KREST-1263 Exclude a vulnerable jackson-mapper-asl dependency from avro 1.8.2 in 5.3.x.

README.md, pom.xml
This property was used in repository/url definition.  This causes a problem with resolution of the parent project/pom, since
property-evaluation occurs in Maven after the parent project is resolved.
`Dockerfile` which can be used to test can't/can build-from-source (without external repository configuration):
```
FROM maven:3.6.3-openjdk-8
RUN useradd -m build
USER build
COPY --chown=build . /home/build/src
WORKDIR /home/build/src
RUN mvn package -U
```
Prior to this change:
```
> [5/5] RUN mvn package -U:
#7 1.995 [INFO] Scanning for projects...
#7 2.343 Downloading from central: https://repo.maven.apache.org/maven2/io/confluent/rest-utils-parent/5.0.0/rest-utils-parent-5.0.0.pom
#7 3.749 [ERROR] [ERROR] Some problems were encountered while processing the POMs:
#7 3.749 [FATAL] …
```
=> KREST-46: Removed property ${confluent.maven.repo}

kafka-rest/pom.xml, pom.xml
We want to run sufficient tests to be confident the package is viable, but running tests during packaging is just repeating work done during development. Start by reducing the tests run, with a plan of running just a specific smoke test.
=> KREST-1334 Reduce time testing during ce-kafka-images packaging

kafka-rest/src/main/java/io/confluent/kafkarest/extension/ResourceAccesslistFeature.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/accesslist/ResourceAccesslistTestBase.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/accesslist/ResourceAllowlistAndBlocklistTest.java
Because OPTIONS requests are handled by the default jersey
OptionsMethodProcessor, the allowlist feature does not play nice with
it, as it will block anything that is not annotated with something
that is in the allowlist, and the jersey processor is clearly not. We
also have the problem that this processor handles OPTIONS requests for
all endpoints, and we don't have a good way on intercepting it making
it work nice with the allowlist.
The current stop gap solution is to allow OPTIONS for all
endpoints. We can investigate better solutions afterwards.
=> KREST-1458: Always allow OPTIONS requests.

kafka-rest/src/main/java/io/confluent/kafkarest/extension/ResourceAccesslistFeature.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/accesslist/ResourceAccesslistTestBase.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/accesslist/ResourceAllowlistAndBlocklistTest.java
Because OPTIONS requests are handled by the default jersey
OptionsMethodProcessor, the allowlist feature does not play nice with
it, as it will block anything that is not annotated with something
that is in the allowlist, and the jersey processor is clearly not. We
also have the problem that this processor handles OPTIONS requests for
all endpoints, and we don't have a good way on intercepting it making
it work nice with the allowlist.
The current stop gap solution is to allow OPTIONS for all
endpoints. We can investigate better solutions afterwards.
Chery-pick of https://github.com/confluentinc/kafka-rest/pull/862.
=> Always allow OPTIONS requests. (#862)

kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestApplication.java, kafka-rest/src/main/java/io/confluent/kafkarest/backends/kafka/KafkaModule.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/ResourcesFeature.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v2/ConsumersResource.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v2/V2ResourcesFeature.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/KafkaRestContextIntegrationTest.java
Currently the mechanism used by the various request
processing stages (request/response filters/interceptors and request
handlers) to communicate with each other is
KafkaRestContextProvider. This class owns a thread-local, which is
supposed to keep state per-request-handling-thread (although that's
not 100% true in the presence of async requests). If this thread-local
is not set, than Kafka REST fallsback to a default KafkaRestContext,
which is kept in the KafkaRestContextProvider in a static variable, to
preserve singleton property. This has worked fine so far because up to
this point there has always been a single KafkaRestApplication running
per JVM, but that assumption is not valid anymore. Since the static
cannot isolation the singleton instances accross multiple
KafkaRestApplication …
=> Pass KafkaRestContext to HK2 via ContainerRequestContext.

api/v3/openapi.yaml
Mark the three consumer lag endpoints as preview, ready for kafka-rest cloud documentation update.
There will be a follow on PR for the CP changes, as these will need to be different as there is no x-lifecycle tag available at present,  and they will also need to go into the 700 branch.
=> KREST-1574 Mark consumer lag as preview in openapi docs

kafka-rest/src/test/java/io/confluent/kafkarest/v2/KafkaConsumerManagerTest.java
Previously on #838, we tried to fix testBackoffMsControlsPollCalls,
but we inadvertently made the test too strict. It would assume a
constant number of 2 + (timeoutMillis / backoffMillis) poll calls,
uniformly distributed across timeoutMillis. It would allow only for a
small deviation of -1%/+10% of the expected time for the poll
calls. It turns out these assumptions are too strict and test
consitently fails during PR test runs, and sometimes on branch test
runs.
The new strategy implemented in this PR instead tests that there's no
window of size backoffMillis with more than 2 poll calls, and no
window of size 2 * backoffMillis with no poll calls. This indirectly
tests that the poll calls are distributed across timeoutMillis,
without expecting too much about the actual timing of each poll …
=> Use a more lenient test for testBackoffMsControlsPollCalls.

Jenkinsfile
This should help us with the internal notifications about Kafka REST build status.
=> Update the internal Slack channel name used by Jenkins.

kafka-rest-common/pom.xml
This was found while investigating a vulnerability of `commons-compress` which is a transitive dependency of Avro. Surprisingly this somehow doesn't cause a problem with `commons-compress` on `5.4.x`, but we should definitely get rid of it.
As it is in `kafka-rest-common`, it will probably be merged up to some 5.x version, after which `kafka-rest-common` is no longer available.
=> KREST-1577 Replace a manually set Avro version with the Avro version variable.

api/v3/openapi.yaml
Title needs to change
Contact details are required
x-api/x-audience-x-tags are required
Include both cloud and platform servers, tag the platform ones as x-audience: component-internal so that they are excluded from the cloud docs, and the could one as x-audience: business-unit-internal (arbitrary choice from the options) so it can be excluded from the platform one
Add /kafka/v3 at the front of each path to match the cloud requirements
Change the tags (which make the titles) to all include (v3) to match the cloud requirements
Add `operationId ` which is just a unique string per endpoint, as required by cloud
Add extra `x-lifecycle-stage: Preview` tags at the `get` level for the lag endpoints, and link to the icons indicating preview status in the description
Added in linebreaks to stop …
=> KREST-574 Make openapi.yaml match what is needed for cloud docs

kafka-rest/src/test/java/io/confluent/kafkarest/integration/AuthorizationErrorTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/AvroProducerTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/ClusterTestHarness.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/JsonProducerTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/MetadataAPITest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/ProducerTest.java
These are internal classes and hence can change in incompatible ways.
One such incompatible change committed to Apache Kafka 3.0 is the reason
why we need this in 7.0.x too.
=> Remove ZooKeeperClient/KafkaZkClient usage from tests

kafka-rest/src/test/java/io/confluent/kafkarest/controllers/TopicManagerImplTest.java
A recent change to Apache Kafka (https://github.com/apache/kafka/commit/1d22b0d70686aef5689b775ea2ea7610a37f3e8c) added an overload to `Admin.describeTopics()`, which causes tests in `TopicManagerImplTest` to have ambiguous argument matchers in their mocks. This PR fixes that by specifically matching a `Collection` argument.
=> Fix ambiguous describeConfigs reference in tests

kafka-rest/src/test/java/io/confluent/kafkarest/integration/ClusterTestHarness.java
Recent AK changes related to the removal of ZooKeeper have necessitated the accompanying changes in kafka-rest's tests.
https://github.com/confluentinc/kafka-rest/pull/893 has done that, but unfortunately it also removed the initialization of the `zkConnect` field which then caused an NPE when it ended up being added to a `ConcurrentHashMap` as a `null`.
This attempts to fix the problem by the simplest of approaches: putting back the initialization of `zkConnect`.
Tested locally on `7.0.x` by running a single, randomly chosen integration test:
- Before this change, `KafkaRestStartUpIntegrationTest` failed with NPEs;
- After this change, `KafkaRestStartUpIntegrationTest` passed successfully;
=> Fix NPE causing most integration tests to fail

kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/ProduceActionIntegrationTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/v2/KafkaConsumerManagerTest.java
The two tests ignored here are way too flaky and we have seen at least one occasion were one of them was hiding an even worse problem: https://github.com/confluentinc/kafka-rest/pull/893.
We have added tasks for actually fixing them, but in the meantime they should not be causing as much trouble as they currently are.
=> KREST-1965 Ignore some known very flaky tests

api/v3/openapi.yaml
This adds some common error responses to all endpoints in our OpenAPI spec.
Unfortunately OpenAPI does not provide a nice way to handle these in a single place, so there's a lot of duplication.
- See https://github.com/OAI/OpenAPI-Specification/issues/398, https://github.com/OAI/OpenAPI-Specification/issues/521, https://github.com/OAI/OpenAPI-Specification/issues/566.
The error responses also include some examples that will hopefully be useful for users and developers.
However the examples are by no means exhaustive.
Tested locally with:
```
% swagger-cli validate ~/work/dev/kafka-rest/api/v3/openapi.yaml -d
{
"command": "validate",
"file": "/Users/ddimitrov/work/dev/kafka-rest/api/v3/openapi.yaml",
"options": {
"schema": true,
"spec": true,
"format": 2,
"type": "json",
"wrap": null, …
```
=> KREST-1673 Add error responses to the OpenAPI spec.

pom.xml
Different versions of `google-java-format` will format the code in slightly different ways. This pin is go guarantee we always use the same version everywhere.
=> Pin google-java-format version to 1.11.0.

pom.xml
Our jenkins jobs run Java 8. The latest version of google-java-format that supports Java 8 is 1.7. google-java-format 1.11.0 requires Java 11.
=> Actually pin google-java-format to 1.7.

kafka-rest/src/test/java/io/confluent/kafkarest/integration/AuthorizationErrorTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/ClusterTestHarness.java
Prior to https://github.com/confluentinc/kafka-rest/pull/893, this topic was being created directly in Zookeeper, bypassing Kafka authorization entirely.
Now that we are using Kafka to create the topic, we need to pass through authorization. This changes uses the super-user to create the topic, so that we don't fail authorization.
=> KREST-2260: Use super user when creating topic in AuthorizationErrorTest.

kafka-rest/src/test/java/io/confluent/kafkarest/TestUtils.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/ConsumerLagsResourceIntegrationTest.java
getConsumerLag_returnsConsumerLag produces some records to a couple of
topics, creates a few consumers, then tries to find what is the
consumer lag for each consumer. It turns out it takes some time for
consumer information to propagate everywhere. That means, sometimes,
the test can't find the consumer lags.
By default it tries 3 times. This change makes it try harder: 6 times
instead. There's no data involved in the choice of the new value other
than it is twice the current value.
Assuming 200ms exponential backoff, currently the tries are around
times 0ms, 200ms and 600ms. With the new value of 6 tries, it should
look like 0ms, 200ms, 600ms, 1s400ms, 3s and 6s200ms. That should give
it plenty of time for consumer data to flow everywhere. It will make
tests slower though.
=> KREST-2303: Try harder to find ConsumerLag in integration test.

kafka-rest/src/test/java/io/confluent/kafkarest/TestUtils.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/ConsumerLagsResourceIntegrationTest.java
Most recent test failure: 
https://jenkins.confluent.io/job/confluentinc/job/kafka-rest/job/master/5718/testReport/io.confluent.kafkarest.integration.v3/ConsumerLagsResourceIntegrationTest/getConsumerLag_returnsConsumerLag/
```
[2021-09-13 12:18:29,812] INFO 127.0.0.1 - - [13/Sep/2021:12:18:29 +0000] "GET /v3/clusters/lz7kmpQcRlmmyZFgDkR4JA/consumer-groups/consumer-group-1/lags/topic-1/partitions/0 HTTP/1.1" 404 73 "-" "Jersey/2.34 (HttpUrlConnection 1.8.0_292)" 94 (io.confluent.rest-utils.requests:62)
[2021-09-13 12:18:36,418] ERROR Request Failed with exception  (io.confluent.rest.exceptions.DebuggableExceptionMapper:103)
javax.ws.rs.NotFoundException: Consumer group offsets could not be found.
```
Most recent testbreak ticket: https://confluentinc.atlassian.net/browse/KREST-2408 …
=> KREST-2408: Try longer consumer poll in getConsumerLag integration test

kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/ConsumerLagsResourceIntegrationTest.java
Checked in https://github.com/confluentinc/kafka-rest/commit/74f10d70138777583f4d6f6df82c557558681c04 to 7.0.x to fix `KREST-2408`. When I tried checking in the same changes https://github.com/confluentinc/kafka-rest/pull/906/ to `master` a format issue cropped up, this commit fixes it.
https://jenkins.confluent.io/job/Confluentinc%20Contributors/job/kafka-rest/job/PR-906/2/console
```
12:12:36  [ERROR] Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.12.3:check (default) on project kafka-rest: The following files had format violations:
12:12:36  [ERROR]     src/test/java/io/confluent/kafkarest/integration/v3/ConsumerLagsResourceIntegrationTest.java
12:12:36  [ERROR]         @@ -258,8 +258,7 @@
12:12:36  [ERROR]          ??????????????assertEquals(
12:12:36  [ERROR] …
```
=> MINOR: fix format for spotless check

kafka-rest/src/test/java/io/confluent/kafkarest/integration/ClusterTestHarness.java
Some of kafka-rest's integration tests seem to take more than 80% of their running time just for setup + teardown. In addition to that, during the teardown, some errors that would usually indicate a serious failure can be seen.
This change adds some simple logging that will help identifying the rough ratios of setup to actual test to teardown. It will also help us identify if some usually unexpected error is happening during teardown (which might actually make the error expected).
=> Log setup/teardown of integration tests

kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestConfig.java, kafka-rest/src/test/java/io/confluent/kafkarest/KafkaRestConfigTest.java
This change removes the filtering of all properties not explicitly known to be valid for producer configs. This has demonstrated to be a problem for producer configs before (see [KREST-481](https://confluentinc.atlassian.net/browse/KREST-481)), and now causes a problem for other interceptor configs.
Note that such filtering doesn't work in the general case in the face of extensibility mechanisms that Kafka has (like interceptors) that don't provide a way to register their expected and allowed config in advance.
That same filtering has been left unchanged for the different SR-related configs, despite a history of causing problems there too (see [KREST-1187](https://confluentinc.atlassian.net/browse/KREST-1187)). Removing that same filtering for SR-related configs requires more refactoring …
=> KREST-1936 Remove mask filtering of producer configs.

kafka-rest/src/main/java/io/confluent/kafkarest/controllers/ControllersModule.java
This is to avoid creating a new NoSchemaRecordserializer for each record in a stream. Normally, this instances should be very light and short-lived, so instantiating them should not be a problem. Unfortunately, a new `KafkaJsonSerializerConfig` is created for each `NoSchemaRecordSerializer`, and that thing is everything but light. In special, `AbstractConfig` (super-type) has the bad habit of logging all configs at creation, and when you that doing thousands of times per second, that usually takes a lot of cpu.
=> Bind NoSchemaRecordSerializer as Singleton.

kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestConfig.java, kafka-rest/src/main/java/io/confluent/kafkarest/config/ConfigModule.java, kafka-rest/src/main/java/io/confluent/kafkarest/exceptions/RateLimitGracePeriodExceededException.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/ProduceAction.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/ProduceRateLimiters.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/V3ResourcesModule.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/ProduceRateLimitersTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/ProduceActionTest.java
Before this change, in a multi-tennant cluster, the overall rate limit for produce would be contributed to by all all the sepaate logical clusters.
This meant that one customer could use up the whole quote for the PKC for their single LKC, effectively blocking other customers from using their clusters.
This commit updates the rate limit to be per cluster id, so that each LKC has its own rate limit.
We'll have to carefully consider what to set the limit to, as if there are many LKCs we need to be careful not to swamp the cluster.
=> KREST-2654 Rate limit per clusterId

kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestConfig.java, kafka-rest/src/main/java/io/confluent/kafkarest/config/ConfigModule.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/ProduceRequest.java, kafka-rest/src/main/java/io/confluent/kafkarest/exceptions/RateLimitGracePeriodExceededException.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/ProduceAction.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/ProduceRateLimiter.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/ProduceRateLimiters.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/ProduceRateLimitersTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/ProduceActionTest.java
Extend the existing rest produce rate limiter to also limit on bytes, as well as the original rate count
Tested with a locally running REST producer, as well as the new unit test.
Default bytes per second is 10000
=> KREST-3255: Rate limit REST Produce on size of data

kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestConfig.java, kafka-rest/src/main/java/io/confluent/kafkarest/config/ConfigModule.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/ProduceRequest.java, kafka-rest/src/main/java/io/confluent/kafkarest/exceptions/RateLimitGracePeriodExceededException.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/ProduceAction.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/ProduceRateLimiter.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/ProduceRateLimiters.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/V3ResourcesModule.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/ProduceRateLimitersTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/ProduceActionTest.java
Cherry pick https://github.com/confluentinc/kafka-rest/commit/90e8db21eeeba8b8fb9f1734f105e28f9fff08af and https://github.com/confluentinc/kafka-rest/commit/fd9b2263b86ad0c228d60fb05428ff094c88a881 into the release branch
=> Cherry pick for rate limit based on cluster id and rate limit on bytes into release branch

kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestConfig.java, kafka-rest/src/main/java/io/confluent/kafkarest/config/ConfigModule.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/ProduceAction.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/V3ResourcesModule.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/ProduceActionTest.java
We suspect there is conention with the Kafka network thread when using the rest producer.  This commit ensures that produce responses are processed on their own thread.
=> KREST-3136 process the produce responses in their own thread

kafka-rest/src/main/java/io/confluent/kafkarest/config/ConfigModule.java
The counter limit for rest produce was being set to 1000, regardless of what the config set it to.  It's not clear where the 1000 default config comes from as we would have expected an error here, but it was due to missing annotations in ConfigModule.
=> KREST-3255 Fix missing annotations for produce limit

kafka-rest/src/main/java/io/confluent/kafkarest/config/ConfigModule.java
The counter limit for rest produce was being set to 1000, regardless of what the config set it to. It's not clear where the 1000 default config comes from as we would have expected an error here, but it was due to missing annotations in ConfigModule.
=> KREST-3255 fix rest producer count limit missing annotations

kafka-rest/src/main/java/io/confluent/kafkarest/exceptions/RateLimitGracePeriodExceededException.java, kafka-rest/src/main/java/io/confluent/kafkarest/ratelimit/RateLimitExceededException.java
The `StatusCodeExceptions` that we throw in great numbers when rate-limiting can take a significant amount of time for filling their stack traces (up to 1% of a flamegraph taken during rate-limiting). These stack traces however are not really interesting for us, as the exceptions themselves always originate from our rate-limiting infrastructure.
The change overrides `fillInStackTrace()` instead of utilizing the `RuntimeException` ctor that takes a `writableStackTrace` flag, because while slightly more efficient, the latter approach is much more cumbersome.
Tested vs a local Kafka REST instance loaded using JMeter, by checking that the `java/lang/RuntimeException.<init>` -> `java/lang/Exception.<init>` -> `java/lang/Throwable.<init>` -> `java/lang/Throwable.fillInStackTrace` stack trace …
=> KREST-3430 Optimize rate-limiting exceptions

.github/CODEOWNERS
Email from Mayuri Shinkar
By 02/01/2022 - Please ensure that your repo has a CODEOWNERS file defined and present in your repository Note: (If your repo does not have a CODEOWNERS file you need to create one by 02/01/2022 else you won’t be able to commit to your repo after this change)
=> KREST-3636 all repos need a codeowners file - kafka-rest-eng set

kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestConfig.java
Default for number of bytes per second was 10K not 10MB
All our other rate limiters are off by default, so I've updated the produce limiter to match
=> KREST-3255 Fix typo in 10 MB

kafka-rest/src/test/java/io/confluent/kafkarest/ratelimit/Resilience4jRateLimitTest.java
This test flakes out both locally and on Jenkins. We should fix it, but as I'm preoccupied with other high priority problems (KREST-3001) right now, it makes sense to at least prevent this from adding noise to our build results.
See https://jenkins.confluent.io/job/confluentinc/job/kafka-rest/job/7.1.x/175/testReport/junit/io.confluent.kafkarest.ratelimit/Resilience4jRateLimitTest/rateLimitWithClassCost/history/ and https://jenkins.confluent.io/job/confluentinc/job/kafka-rest/job/master/6720/testReport/io.confluent.kafkarest.ratelimit/Resilience4jRateLimitTest/rateLimitWithClassCost/history/ for context.
=> Ignore a flaky rate-limit test

kafka-rest/src/test/java/io/confluent/kafkarest/ratelimit/Resilience4jRateLimitTest.java
See #958 and specifically https://github.com/confluentinc/kafka-rest/pull/958#issuecomment-1003126334.
=> Ignore all Resilience4jRateLimitTest tests.

api/v3/openapi.yaml
This fixes a problem in the example request for the Create ACL API (thanks, @nicolasguyomar for raising this) - the request should not contain the typical response fields "kind" and "metadata", which refer to an already existing resource.
The interesting question here is how did this go through the very rigorous OpenAPI validation that we do, which includes `openapi-examples-validator`. The answer is that by default that tool doesn't validate unspecified additional properties - we need the `-n` option for that (see https://github.com/codekie/openapi-examples-validator#usage). With that option, the problem is detected (along with a couple of others, that should be addressed separately).
I'll update our OpenAPI testing guidelines with that tidbit.
=> KREST-4112 Fix Create ACL request example.

kafka-rest/src/test/java/io/confluent/kafkarest/ratelimit/GuavaRateLimitTest.java
Unfortunately the GuavaRateLimitTest is also failing a lot - 4 out of 15 times on master - so it also needs to be disabled first, and at some point - fixed.
=> Disable the very flaky Guava rate-limiter tests.

pom.xml
I've tested on a non-confluent laptop (which has a brand new maven version) and the build failed UNLESS I used https, as mvn refused to resolve the unsecure repository :)
Build pulls artefacts successfully with https.
=> KREST-3836 update maven to pull from https

kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/AclsResource.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/AclsResourceIntegrationTest.java
This change prevents the simplest DELETE request (a no-parameter one) from deleting all ACLs. This is done by a simple change of the default value for the resource_type query param from a wildcard match to an invalid one (one that requires explicit input from the user).
- In addition to that, some inconsistencies in the delete request validation have been addressed.
For some reason, requests with partially filled query params are not currently hitting the "Delete ACL" endpoint - it should be investigated whether that's due to a testing problem, Jersey bug, or something else.
=> KREST-4113 Don't delete all ACLs if an empty DELETE request is received.

kafka-rest/src/test/java/io/confluent/kafkarest/README.md, kafka-rest/src/test/java/io/confluent/kafkarest/integration/KafkaModuleOverridingTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/SchemaRegistrySaslInheritTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v2/SchemaProduceConsumeTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/ProduceActionIntegrationTest.java
Some of our integration tests were missing the "IntegrationTest" tag, so it wasn't possible to run them individually.
I've added a testing readme to explain how to run the tests individually, and also how to run them repeatedly, as requested.
=> KREST-4466 Run tests individually and repeatedly

kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestConfig.java
For the idempotent producer, some errors are permanent, meaning the producer instance becomes unusable afterwards. Authorization errors are one of these. This behaviour disagrees with the Kafka REST model, which assumes the producer to be stateless across requests. Until we either adapt Kafka REST to the idempotent model, or authorization errors become non-fatal, we will disable idempotent producers in Kafka REST.
=> Disable producer idempotency until KAFKA-13668 is fixed.

kafka-rest/src/test/java/io/confluent/kafkarest/integration/ClusterTestHarness.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/MetadataAPITest.java
Fix typo where we were checking the wrong response object
restServer sees "address already in use" very occasionally - if this happens shut down, wait and try again
On a restart, the original metrics have already been registered and may be be cleared up yet, so we need to clear them from the application.  I've gone belt and braces approach in clearing the metrics.
Sometimes the Kafka metric server is still left behind - so we close this off explicitly too with server.metrics().close();
Sometimes kafka hasn't quite finished making the topics, so when we get the topics, only the first is returned, so these components are run with a testWithRetry. There is an analysis of the Kafka debug logs in the jira that describes this in more detail.
=> KREST-4577 Fix Metadata API Test

kafka-rest/src/main/java/io/confluent/kafkarest/v2/KafkaConsumerReadTask.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/AbstractConsumerTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/ClusterTestHarness.java
KafkaConsumerReadTask
- exception stack trace not logged, added in so we have a starting point for debugging the intermittently failing test
AbstractConsumerTest
- a 404 is returned somewhere in startConsumerMessages (can't prove where, but one of the assertOKResponses fails with a 404) so check for the 404 on both, and then retry after a pause if it is returned.  Fail the second time
- The number of messages consumed doesn't always match how many we expect.  I could reproduce this locally, and a single retry didn't always help, so I've added in two.  If it still fails we can look at reworking this a different way
- consumeForTimeout is inherently flakey as it is so reliant on times.  I've doubled the wait period slack to 1s, from 501ms to see if that helps at all, but otherwise we will …
=> KREST-4605 Deflake all the tests that extend AbstractConsumerTest

kafka-rest/pom.xml, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/ConsumerGroupLagSummariesResourceIntegrationTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/ConsumerGroupsResourceIntegrationTest.java, pom.xml
ConsumerGroupLagSummariesResourceIntegrationTest saw consumerGroupId=consumer-group-1, maxLag=3, totalLag=3 when it was expecting consumerGroupId=consumer-group-1, maxLag=6, totalLag=9
I can't reproduce locally but my best guess is that the lags just haven't been updated yet (see the issue for an explanation of the test flow), so give it another chance
listConsumerGroups_returnsConsumerGroups saw partitionAssignor=range, state=STABLE when it was expecting partitionAssignor=, state=PREPARING_REBALANCE
I would say that either is valid, so I've added in the "anyOf" matcher
=> KREST-4608 unflake consumergroup tests

kafka-rest/src/test/java/io/confluent/kafkarest/integration/ConsumerTimeoutTest.java
This test sets a consumer instance timeout of 1000ms, creates a consumer instance with that timeout, does some consuming, and then waits 2100ms before doing the next consume.
It expects that the consume will fail because the consume instance has timed out - it should expire after 1s and the test waits for 2.1s which should be plenty even allowing for slowness.
However, if you look in the consumer instance timeout code, there is a 1000ms wait between cleanup cycles.
So, it’s conceivable that we could wait up to 2000ms for the consumer instance to be cleared.
The current wait in the test is 2100ms (instanceTimeout + slackTime) before checking if the consumer has expired, which doesn’t account for any slowness in the machine.
I've increased the slack time
=> KREST-4783 Increase slack in consumer timeout test

kafka-rest/src/main/java/io/confluent/kafkarest/DefaultKafkaRestContext.java, kafka-rest/src/main/java/io/confluent/kafkarest/Errors.java, kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestConfig.java, kafka-rest/src/main/java/io/confluent/kafkarest/backends/schemaregistry/SchemaRegistryModule.java, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/ControllersModule.java, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/RecordSerializerFacade.java, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/SchemaManagerImpl.java, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/SchemaManagerThrowing.java, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/SchemaRecordSerializerImpl.java, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/SchemaRecordSerializerThrowing.java, kafka-rest/src/main/java/io/confluent/kafkarest/exceptions/RestConstraintViolationExceptionMapper.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/ProduceAction.java, kafka-rest/src/main/java/io/confluent/kafkarest/response/StreamingResponse.java, kafka-rest/src/test/java/io/confluent/kafkarest/controllers/RecordSerializerFacadeTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/controllers/SchemaManagerImplTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/controllers/SchemaRecordSerializerTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/ProduceActionTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/response/StreamingResponseTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/unit/DefaultKafkaRestContextTest.java
This cherry-picks the changes addressing various HTTP 500 errors in Kafka REST, including correctly closing resources and the response sink if an unmapped exception happens during Jackson record iteration.
These changes address the resource leakage causing [RCCA-5716](https://confluentinc.atlassian.net/browse/RCCA-5716).
The only conflict during the cherry-picking was a fairly trivial one related to imports.
The cherry-pick has been tested locally by ensuring that producing the following malformed record:
```
{
value":
{
"type": "JSON",
"data": "A"
}
}
```
- throws HTTP 500 and leaks a connection and Kafka network thread before the cherry-pick
- throws HTTP 400 and doesn't leak after the cherry-pick
P.S. While the commit and the old PR say …
=> RCCA-5716 Cherry-pick "KREST-3537: Fix HTTP 500 errors in Produce V3. (#960)" into v0.2621.x

kafka-rest/src/test/java/io/confluent/kafkarest/integration/ConsumerTimeoutTest.java
The consumeTimeout test is failing in the 7.1 CP tests because of huge gaps between API calls.
There is 0.5s between the POST to create the consumer group and the subscription and then over 2 seconds between the subscription create and the GET that does the consume
Before this change the instance expiry (how long the consumer group is kept for) was set to 1s, and so the consumer group was timing out before the GET happened, resulting in a 404.
This PR increases the instance timeout to 3.5 s, which unfortutately adds 2.5s to the consumeTimeout test run time, but won't impact the run time of any other tests.
=> KREST-4825 Huge timeout in consume test

kafka-rest/src/main/java/io/confluent/kafkarest/exceptions/StacklessCompletionException.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/ProduceAction.java
This cherry-picks the changes of https://github.com/confluentinc/kafka-rest/pull/973 into the latest `ce-kafka-images` release branch.
These changes remove a significant Produce v3 rate-limiting overhead (well over 10% of the CPU profiler in specific cases) and are very important for Kafka REST's upcoming Produce v3 EA release to Multi-tenant clusters.
- They also depend on https://github.com/confluentinc/kafka-rest/pull/990 which has already been merged to the 2816 branch.
The changes are fairly simple, isolated, and have been tested fairly well in [the original JIRA](https://confluentinc.atlassian.net/browse/KREST-4356).
=> Cherry-pick "KREST-4356 Optimize CompletionExceptions when rate-limiting (#973)" into v0.2816.x

kafka-rest/src/main/java/io/confluent/kafkarest/controllers/AclManager.java, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/AclManagerImpl.java, kafka-rest/src/test/java/io/confluent/kafkarest/controllers/AclManagerImplTest.java
This PR lays the ground work for a later PR to allow multiple ACLs to be created in a single request. 
It adds a new method createAcls that takes multiple Acl objects and creates them.
Tested with unit tests
=> KEXP-280 new manager method to submit multiple ACLs for creation 

kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/ProduceRateLimiters.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/ProduceRateLimitersTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/ProduceActionTest.java
Testing showed that putting the global rate limiter first results in reduced CPU load.
=> KREST-4979 reverse order of produce global rate limiters

kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestConfig.java, kafka-rest/src/main/java/io/confluent/kafkarest/config/ConfigModule.java, kafka-rest/src/main/java/io/confluent/kafkarest/ratelimit/RateLimitModule.java, kafka-rest/src/main/java/io/confluent/kafkarest/ratelimit/RequestRateLimiterProduceBytesGlobalFactory.java, kafka-rest/src/main/java/io/confluent/kafkarest/ratelimit/RequestRateLimiterProduceCountGlobalFactory.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/ProduceRateLimiters.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/ProduceRateLimitersTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/ProduceActionTest.java
This cherry-picks the two changes around the Produce v3 global rate limiter:
- #993 which introduced the global rate limiter;
- #997 which made it the first rate limiter to be hit (before the per-tenant rate limiters);
These changes increase the safety of the Produce v3 API for multi-tenant clusters, where the original per-cluster rate limiting does not impose a clearly-defined global rate limit, that can correspond to the available instance capacity.
The changes have been tested relatively extensively with our latest performance testing experiments, done by @ehumber and @rigelbm.
=> KREST-4961 Cherry-pick Kafka REST global Produce v3 rate limiter into v0.3137.x

kafka-rest/src/main/java/io/confluent/kafkarest/v2/KafkaConsumerState.java, kafka-rest/src/test/java/io/confluent/kafkarest/v2/KafkaConsumerManagerTest.java
this is to fix the issue: #341
when rebalancing starts by multiple instances in a consumer group, a pseudo deadlock condition occurs:
thread a. (Consumer Expiration Thread)
1) acquired the KafkaConsumerManager instance (lock A) within KafkaConsumerManager$ExpirationThread::Run
2) waiting to acquire the KafkaConsumerState instance (lock B) within KafkaConsumerState::expired
thread b.
1) acquired the KafkaConsumerState instance (lock B) within KafkaConsumerState::hasNext in KafkaConsumerReadTask::addRecords
2) waiting to acquire the ?? (lock C) within KafkaConsumer::poll(0) by rebalancing
thread c.
1) acquired the ?? (lock C) within jettyHandler
2) waiting to acquire the KafkaConsumerManager instance (lock A) within KafkaConsumerManager::getConsumerInstance in readRecords
a cyclic lock …
=> Fix(#341): Remove deadlock when rebalancing by multiple consumer instances

api/v3/openapi.yaml, kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/ProduceResponse.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/ProduceAction.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/ProduceActionTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/response/StreamingResponseTest.java
Before this change, produce responses did not include an http status code if they were successful, only for error responses
This meant that code generated to match the openapi spec can't easily differentiate between a success and a failure response.
Ideally we'd have added in a status_code for success and failure cases, but there is an existing ErrorResponse that is used by all existing endpoints, and it seems overkill (and probably not the right thing to do for consistency) to put in place custom error handling for produce only, with a different structure
Also, using status_code implies real http statuses, whereas error_code gives us the freedom to use the more detailed 5 digit responses.
The response for a successful produce now looks like …
=> KREST-5385: Add error_code to produce responses.

kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/ProduceAction.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/ProducerMetrics.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/ProducerMetricsTest.java
In our billing one pager, we have agreement that we will count billing metrics after rate limiting, but before validation of the produce request body.
This PR moves the produce metrics collection point slightly earlier to match that decision.
Currently the bytes metric is an Avg() - so if you send 10 messages of 67, the metric records 67.
I've added a summed count metric to the produce bytes sensor, which is what ce-kafka uses to record bytes as described here https://confluentinc.atlassian.net/wiki/spaces/KREST/pages/2777684595/Billing+metrics#Counting-the-bytes
Waiting on confirmation that this is correct, but I'm fairly sure it is, so raising the PR now.  It's simple to revisit later to swap to eg a Windowed Count or something else if needed.
=> KREST-5637 Add count based byte metrics and move tracking earlier

kafka-rest/src/main/java/io/confluent/kafkarest/entities/AvroProduceRecord.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/PartitionsResource.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/TopicsResource.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v2/PartitionsResource.java
We need to null check the record.getJsonKey() call before calling any methods on it.
5.3.x still passes, the jackson version there is 2.10.5, and the jackson version at 5.4.x is 2.13.2.
I can only assume something has changed between these Jackson versions that has altered how null objects are dealt with (ie really null, rather than returning a json literal null object), possibly as part of  RFC 7159.  However I've not managed to track down the change.
I also had a look to see if there was an annotation I could set on the fields in the AvroProducerRecord to change how it behaves with nulls, but no joy.
Have fixed for all the cases I could find of .isNull being called without a null check.
=> KREST-5096 Fix NPE in Topics Resource when no key, or no value specified

pom.xml
This is needed to enforce gson version. Otherewise, it inherits from com.google.protobuf:protobuf-java-util which is 2.8.6.
=> APPSEC-1156: Patch gson to be 2.9.0

pom.xml
Tested via @javabrett's Dockerfile from #832.
One thing I've noted though - apparently `6.1.1-post` got clobbered, and the #832 changes are again unavailable there (and the aforementioned Dockerfile can again be used to reproduce the problem Brett originally fixed).
I'm not sure how or why did that happen (my guess would be some sort of an automated update process) - I will focus specifically on the HTTP/HTTPS issue here.
@javabrett feel free to file an internal JIRA for looking into the clobbering and eventually reapplying your fix to `6.1.1-post`.
=> KREST-6005 Use HTTPS for public Maven repo URL

kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestApplication.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/ProduceAction.java, kafka-rest/src/main/java/io/confluent/kafkarest/response/JsonStream.java, kafka-rest/src/main/java/io/confluent/kafkarest/response/JsonStreamMessageBodyReader.java, kafka-rest/src/main/java/io/confluent/kafkarest/response/StreamingResponse.java, kafka-rest/src/main/java/io/confluent/kafkarest/response/StreamingResponseFactory.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/ProducerLeakTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/ProduceActionTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/response/StreamingResponseTest.java
JsonParser instantiation, which happens during MappingIterator deserialization, can throw on bad request. This can cause the request scope to not be disposed properly if a `@RequestScoped` resource is injected into a filter before an async resource method is executed. For Kafka REST, this only happens for the Produce Action.
This PR wraps the MappingIterator, so that the JsonParser is only instantiated during the first hasNext/nextValue call.
The PR also adds a test that shows the aforementioned resource leak.
=> KREST-5830: Create a lazy wrapper around MappingIterator for Produce Action.

kafka-rest/src/test/java/io/confluent/kafkarest/integration/AbstractConsumerTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/ClusterTestHarness.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/ConsumerAvroTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/ConsumerBinaryTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/ConsumerJsonTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/ConsumerTimeoutTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v2/SchemaProduceConsumeTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v2/SeekToTimestampTest.java, kafka-rest/src/test/resources/log4j.properties
Looking at the logs for this intermittent failure, the consumer attempts to consume messages 4 times, over a course of 15 seconds, but only gets one record, from the second attempt.  Each GET returns a 200, the failed consumes just time out, not finding any records.
There are no logs relating to the produce (these are only written at trace level for the produce client) so it’s not possible to tell if the produces all went through - is it the produce failing or the consume that's causing the problem here?
Produce is acks=all, the consumer’s auto.offset.reset is the default, which is latest.
I’ve added in diagnostics plus some guesses at fixing the problem:
trace level logging for the produce and consume clients so we can diagnose failures more easily
logging of which offset we are getting …
=> KREST-4687 avro consume still fails

kafka-rest/src/test/java/io/confluent/kafkarest/integration/ClusterTestHarness.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/TopicsResourceIntegrationTest.java
Most of the test flakes in this class are due to failures in the setup and the topics not being created.
I can't reproduce this locally unfortunately, but I have put in a pile of retry logic to allow more time, and then have another try at creating the environment.
Also add in a test retry for a flakey test.
=> KREST-4591 add topic recreate logic to cluster test harness

kafka-rest/src/test/java/io/confluent/kafkarest/integration/ClusterTestHarness.java
As #978 got merged roughly together with #1022, an empty catch block validation error that it introduced managed to sneak in.
This change addresses that.
I'll be merging this change immediately to fix the build.
=> Fix Checkstyle empty catch block error.

kafka-rest/src/main/java/io/confluent/kafkarest/v2/KafkaConsumerState.java, kafka-rest/src/test/java/io/confluent/kafkarest/v2/KafkaConsumerManagerTest.java
This backports @merrygoround-of-life's fix from #942 in `5.4.x` as although the deadlocking synchronization changes were originally introduced in `6.0.x` (where #942 has landed), they were also backported to `5.2.x` (with #777) and `5.4.x` (with #778).
=> Backport consumer deadlock fix to 5.4.x

kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestConfig.java, kafka-rest/src/main/java/io/confluent/kafkarest/config/ConfigModule.java, kafka-rest/src/main/java/io/confluent/kafkarest/response/StreamingResponse.java, kafka-rest/src/main/java/io/confluent/kafkarest/response/StreamingResponseFactory.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/ProduceActionTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/response/StreamingResponseTest.java
During our release review last year, one of the requests was to ensure that any long running connections are disconnected periodically.
Kafka does this for non-rest clients in https://github.com/confluentinc/ce-kafka/pull/3252 (which wasn't merged but has some interesting comments) and https://github.com/confluentinc/ce-kafka/pull/3292
The intent of this PR is to disconnect all streaming produce connections 24 hours after they were first made.  Once the stream has reached this age, the next message to arrive will get a 408 request timeout with message "Streaming connection open for longer than allowed: Connection will be closed." 
Suggestions please for a better http status code, there is nothing that I could find that matches what we are doing.
We want to try and respond to any …
=> KREST-2655 Simple version of disconnect

kafka-rest/src/test/java/io/confluent/kafkarest/v2/PartitionsResourceTest.java, pom.xml
This change will cause `JerseyTest` to run on a random port instead of the default 9998. This should work around the fact the ports are possibly leaking between tests.
=> APIF-2768: Workaround for "Failed to bind to 0.0.0.0/0.0.0.0:9998" error.

kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/ProducerMetrics.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/ProducerMetricsTest.java
In standalone kafka-rest the metricsTags are empty.
In ce-kafka-rest we inject the LKC tenant id as a tag
This PR adds the tenant tag to the end of the sensor name, so that each LKC has its own sensor.
This level of granularity is OK (rather than per individual request) because billing is done per lkc.
We also don't want a sensor per request as that would be a LOT of sensors.
Each sensor expires after being left unused for 1 hour.  Streams are disconnected after 30s if they are unused, so 1 hour should be OK.
I've tested this by copying over the ce-kafka-rest code to the V3ResourceModule and getting it to make a new LKC tag every other request that comes in
- each lkc sensor has two requests written to it, then the next sensor is made.
- the original sensor is not updated when the later …
=> KREST-7005 use a sensor object per request - but shared per LKC id

kafka-rest/src/main/java/io/confluent/kafkarest/v2/KafkaConsumerState.java
#1035 replaced a usage of the deprecated [KafkaConsumer#poll(long)](https://github.com/apache/kafka/blob/0507597597e1d2d9adaa33b87e5ea509e12fd2f0/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java#L1167) API with the [KafkaConsumer#poll(Duration)](https://github.com/apache/kafka/blob/0507597597e1d2d9adaa33b87e5ea509e12fd2f0/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java#L1214) API in the internals of Kafka REST's Consume v2 API. There is a slight difference in behavior between the two KafkaConsumer APIs related to blocking during consumer rebalancing.
- See [this wiki](https://cwiki.apache.org/confluence/display/KAFKA/KIP-266%3A+Fix+consumer+indefinite+blocking+behavior#KIP266:Fixconsumerindefiniteblockingbehavior-Consumer#poll) for more …
=> Revert replacement of poll(Duration) with poll(long)

api/v3/openapi.yaml
This PR targets 7.2.0-post for the change on the platform docs to be visible (just targeting `master` won't work on platform)
- https://confluentinc.atlassian.net/browse/DOCS-16947
- https://confluentinc.atlassian.net/browse/DOCS-14660
Related PR for platform: https://github.com/confluentinc/ce-kafka-rest/pull/347
Related PRs for the same change on Cloud API docs:
- https://github.com/confluentinc/ce-kafka-rest/pull/342
- https://github.com/confluentinc/api/pull/730
Signed-off-by: Victoria Bialas <vicky@confluent.io>
=> DOCS-16947, DOCS-14660 Produce v3 API from EA to Open Preview (platform, api repo, kafka-rest)

api/v3/openapi.yaml, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/AclManager.java, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/AclManagerImpl.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/CreateAclBatchRequest.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/CreateAclBatchRequestData.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/AsyncResponses.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/AclsResource.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/CreateAclBatchAction.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/V3ResourcesFeature.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/AclsResourceIntegrationTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/AclsResourceTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/CreateAclBatchActionTest.java
This commit
- updates the kafka-rest openapi.yaml to include the changes for batch acl create which are required by the UI
- It ports the code from Tom's ce-kafka-rest PR into kafka-rest, making this a new publically available API.  This feels like the right thing to do, because it's a simple API (just a wrapper around the individual create API comment), it was odd to split to very linked APIs across two repos (and this made our lives much harder wrt eg the integration test and the openapi doc).
- Add a null check in the single create ACL to avoid a NPE and the subsequent 500 error being returned to the user.  Unfortunately this typed the cyclomatic complexity of all the valid payload checks in the createAcl class over the limit, so I had to pull them out into a separate method.
- Add a …
=> KREST-7275 update openapi changes for batch acl

kafka-rest/src/main/java/io/confluent/kafkarest/common/KafkaFutures.java, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/PartitionManagerImpl.java, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/ReplicaManagerImpl.java, kafka-rest/src/test/java/io/confluent/kafkarest/controllers/PartitionManagerImplTest.java
If there are stray partition of topic, the user will see 404, but the user can't see which topic has stray partition. We added the following information related to this:
1. add a debug line that logs the response from getLogDirs ```[2022-09-07 12:16:44,626] DEBUG Describe log Dirs/tmp/kafka-logs/server0(error=NONE, replicas={tst-53=(size=0, offsetLag=-1, isFuture=false), tst-86=(size=0, offsetLag=-1, isFuture=false), tst-20=(size=0, offsetLag=-1, isFuture=false), test-32=(size=0, offsetLag=0, isFuture=false), tst-111=(size=0, offsetLag=-1, isFuture=false), test-98=(size=0, offsetLag=0, isFuture=false), tst-45=(size=0, offsetLag=-1, isFuture=false), tst-78=(size=0, offsetLag=-1, isFuture=false), tst-12=(size=0, offsetLag=-1, isFuture=false), test-24=(size=0, offsetLag=0, isFuture=false), …
```
=> Log Describe log Dirs and log the topic name causing a 404 anyway

kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/ProduceAction.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/TopicsResource.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/TopicsResourceIntegrationTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/ProduceActionTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/TopicsResourceTest.java
When create topics without payload, a general server errors will return currently: 
```
curl -X POST http://localhost:9391/v3/clusters/kZ7pDeiQSS-9eRtOXlWSMQ/topics -H "Authorization: Basic ABC"
returns a {"error_code":500,"message":"Internal Server Error"}%
```
But this should be a user error, after the user adds payload, it should be resolved. The return message and error code should be clear to mention that.
Result for local manual test.
```
curl -X POST http://localhost:8082/v3/clusters/vD3GG4PqT0-C1UcpR1j-Ag/topics -H "Authorization: Basic ABC" -H "Content-Type:application/json"
{"error_code":42206,"message":"Payload error. Null input provided. Data is required."}% 
``` 
Result of unit test:
```
mvn -Dtest=TopicsResourceTest test
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: …
```
=> NPE when post to topics endpoint without payload

kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/ProduceActionIntegrationTest.java
After pint merged https://github.com/confluentinc/kafka-rest/pull/1072 from 6.2.x to master, all the branches looks good except the 7.3.x
This is the error
```
13:34:39  [ERROR] /home/jenkins/workspace/confluentinc_kafka-rest_7.3.x/kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/ProduceActionIntegrationTest.java:225: Line is longer than 100 characters (found 247). [LineLength]
```
=> Fix the line longer than 100 characters issue

kafka-rest/src/test/java/io/confluent/kafkarest/unit/AvroConverterTest.java
The AvroUtils.toJson has been enhanced to handle primitives, so the test here can be removed
=> Remove obsolete Avro test

kafka-rest/src/test/java/io/confluent/kafkarest/integration/AuthorizationErrorTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/ClusterTestHarness.java
KAFKA-14334 changed a kafka.utils.TestUtils method [by adding a default argument](https://github.com/confluentinc/kafka/commit/dbf5826cd545820652ed6d136727aa80a03f4f54#diff-b8f9f9d1b191457cbdb332a3429f0ad65b50fa4cef5af8562abcfd1f177a2cfeR216-R218) (Scala). Unfortunately this is a breaking change for Java downstream dependencies.
Verified with a local `mvn clean package -DskipTests` build.
=> Fix build breakage caused by KAFKA-14334

api/v3/openapi.yaml, kafka-rest/pom.xml, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/TopicManager.java, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/TopicManagerImpl.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/PartitionCountRequest.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/PartitionsCountRequest.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/TopicsResource.java, kafka-rest/src/test/java/io/confluent/kafkarest/controllers/TopicManagerImplTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/ClusterTestHarness.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/TopicsResourceIntegrationTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/TopicsResourceTest.java, pom.xml
Call looks like
```
curl -X PATCH http://localhost:8082/v3/clusters/3W-2oFuqSYuErBzrRrTKyw/topics/bob  -H "Content-Type: application/json" -d '{"partition_count":"10"}'  | jq
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   688    0   664  100    24   6036    218 --:--:-- --:--:-- --:--:--  6254
{
"kind": "KafkaTopic",
"metadata": {
"self": "http://localhost:8082/v3/clusters/3W-2oFuqSYuErBzrRrTKyw/topics/bob",
"resource_name": "crn:///kafka=3W-2oFuqSYuErBzrRrTKyw/topic=bob"
},
"cluster_id": "3W-2oFuqSYuErBzrRrTKyw",
"topic_name": "bob",
"is_internal": false,
"replication_factor": 1,
"partitions_count": 10,
"partitions": {
"related": "http://localhost:8082/v3/clusters/3W-2oFuqSYuErBzrRrTKyw/topics/bob/partitions …
```
=> KREST-3009 Add ability to update partition count on a topic

api/v3/openapi.yaml, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/AbstractConfigManager.java, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/TopicConfigManager.java, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/TopicConfigManagerImpl.java, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/TopicManager.java, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/TopicManagerImpl.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/AlterConfigBatchRequestData.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/CreateTopicRequest.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/AlterTopicConfigBatchAction.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/TopicsResource.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/TopicsResourceIntegrationTest.java
This change introduces an additional "validate only" parameter to the requests for two important topic APIs:
- Create Topic
- Batch Alter Topic Config
When this parameter, which is a boolean flag, is set, the corresponding operation would be dry-run, i.e. its execution would be validated as if its actually run, but there would be no side effects from the operation. E.g. if run in that mode, a Create Topic request won't actually create a topic.
As this requires just using simple overloads of the corresponding Admin APIs, this change mostly focuses on introducing the new parameters in minimally disruptive way in exchange for some verbosity and maybe even redundancy.
- E.g. none of the existing tests had to be changed, including the resource test, which expect specific manager calls, and the …
=> KREST-8518 Add dry-run/validate-only versions of some topic APIs

kafka-rest/src/main/java/io/confluent/kafkarest/controllers/AbstractConfigManager.java, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/TopicConfigManagerImpl.java
ce-kafka-rest happens to have a config manager that has defined on its own a validateOnly version of safeAlterConfigs, so introducing one in the base config manager (with a final modifier) causes a breakage.
For now let's avoid the breakage by renaming the base method and avoiding the unwanted override, and later we can consider whether it's better to remove the ce-kafka-rest method and use the base method instead.
- The problem could also be addressed by just removing the `final` modifier of the newly added base method so that an override does happen, but that seems slightly more invasive than just isolating the newly added base method.
- The ce-kafka-rest downstream validation will probably still fail because of a new unrelated problem that sneaked in the last hours.
Tested by local …
=> Address a coincidence causing a build breakage

kafka-rest/src/test/java/io/confluent/kafkarest/integration/ClusterTestHarness.java, kafka-rest/src/test/java/io/confluent/kafkarest/testing/SchemaRegistryFixture.java
This PR should fix the issue that encountered in https://github.com/confluentinc/kafka-rest/runs/10398565843.
=> Make sure SchemaRegistryRestApplication check for leader election finish

pom.xml
The build currently fails with:
```text
[ERROR] Failed to execute goal org.owasp:dependency-check-maven:6.1.6:check (default) on project kafka-rest-parent: Fatal exception(s) analyzing kafka-rest-parent: One or more exceptions occurred during analysis:
```
This was fixed in common via https://github.com/confluentinc/common/pull/496, but that doesn't help with the v0.4388.x cloud release branch.
=> Set dependency.check.version to 7.4.4 to fix build failure (v0.4388.x)

kafka-rest/src/main/java/io/confluent/kafkarest/v2/KafkaConsumerState.java
Original fix was: https://github.com/confluentinc/kafka-rest/pull/942/
However, we didn't resolve the conflict correctly causing the same issue to resurface.
=> Incorrect merge conflict resolution lead to buggy synchronization block

kafka-rest/src/main/java/io/confluent/kafkarest/controllers/SchemaManagerImpl.java, kafka-rest/src/test/java/io/confluent/kafkarest/controllers/SchemaManagerImplTest.java
* KREST-8965 Fix test
SchemaRegistry now allows "null" schema, handle that.
=> cherry-pick: fix test (#1115)

kafka-rest/src/test/java/io/confluent/kafkarest/integration/AuthorizationErrorTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/ClusterTestHarness.java
KAFKA-14334 changed a kafka.utils.TestUtils method by adding a default argument (Scala). Unfortunately this is a breaking change for Java downstream dependencies.
=> Fix build breakage caused by KAFKA-14334 (#1083)

api/v3/openapi.yaml
According to [this support ticket](https://confluent.zendesk.com/agent/tickets/122747) and this[ Docs Jira](https://confluentinc.atlassian.net/browse/DOCS-18055), GET broker configs returns only the dynamic configurations for the brokers.
The change rendered in HTML:
=> DOCS-18055 -  `List All Broker Configs` to `List Dynamic Broker Configs`

kafka-rest/src/main/java/io/confluent/kafkarest/controllers/TopicManager.java, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/TopicManagerImpl.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/Topic.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/TopicsResource.java, kafka-rest/src/test/java/io/confluent/kafkarest/controllers/TopicManagerImplTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/TopicsResourceIntegrationTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/TopicsResourceTest.java
Previously the response for v3 CreateTopic only contained the partition count and replication factor if they were supplied in the request. Now, this information is returned in the response always. This mirrors the behaviour of the Kafka AdminClient.createTopics.
=> KREST-1797 - CreateTopic returns partitions and repl factor

api/v3/openapi.yaml, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/TopicManagerImpl.java
The example for `replicas_assignments` for `POST .../v3/clusters/{}/topics` was very wrong. You need to provide a map.
=> KREST-4757: Fix example for replicas_assignments

kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/TopicsResource.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/TopicsResourceTest.java
An unvalidated topic name was being used in a code path which could execute before Kafka had rejected the topic name during topic creation. The topic name is validated using a Kafka utility method which prevents this unfortunate situation.
Previously, an invalid topic name (specifically which was not URL-safe) caused an HTTP 500, but now an invalid topic name gives HTTP 422.
=> KREST-2863 - Validate topic name in createTopic

kafka-rest/src/main/java/io/confluent/kafkarest/extension/EnumConverterProvider.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/AclsResourceIntegrationTest.java
The enumeration converter threw an exception containing a useful message which was obliterated by the chain of exception handlers.
=> KREST-8332 - Better error messages for query parameters

kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/ProduceAction.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/ProduceActionTest.java
The produce API endpoint can be used with or without specifying a partition ID. If a partition ID is specified, it must be non-negative. Before this change, a negative partition ID would result in an exception from the constructor for `ProducerRecord` which was translated into HTTP 500. But because it's a result of an incorrect request, it should be HTTP 4xx.
The change validates that a supplied partition ID is indeed non-negative before going anywhere near Kafka. The HTTP status code for a negative partition ID is 404.
=> KREST-5711 - Non-negative partition id for produce

kafka-rest/src/main/java/io/confluent/kafkarest/controllers/PartitionManager.java, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/PartitionManagerImpl.java, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/ReplicaManagerImpl.java, kafka-rest/src/test/java/io/confluent/kafkarest/controllers/ReplicaManagerImplTest.java
The `GET v3/clusters/{}/brokers/{}/partition-replicas` operation issues multiple calls to AdminClient. In the event that a topic is deleted between the first call and the later calls, it's possible that topic-partitions found in the first call are not found in the later calls. The appropriate action in this case is just to remove them from the response, rather than failing with a 404.
=> KREST-6569 - Cope with partitions disappearing

pom.xml
Remove the SnakeYaml definition from the dependency management to use the latest version defined in common. See: https://github.com/confluentinc/common/pull/514
=> KREST-9942: Remove SnakeYaml from dependency management

api/v3/openapi.yaml, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/ClusterConfigManagerImpl.java, kafka-rest/src/test/java/io/confluent/kafkarest/controllers/ClusterConfigManagerImplTest.java
The "cluster config" operations were inaccurately described. They're really KIP-226 which introduced "dynamic cluster-wide broker configuration parameters". Updated the OpenAPI specification to make this clear, and a bunch of other small improvements. Also changed the delete operation so that it fails if the config does not exist.
=> KREST-8221 Dynamic broker config improvements

kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/ProduceActionIntegrationTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/ProduceRateLimitersTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/testing/DefaultKafkaRestTestEnvironment.java, kafka-rest/src/test/java/io/confluent/kafkarest/testing/KafkaRestFixture.java
1. In ProduceActionIntegrationTest, add integration-test for the 4 rate-limits. The happy-path testing, i.e. rest calls below threshold succeed are already covered by the existing tests. The 4 new tests, 1 per rate-limit config, sets a very low rate-limit of "1", to deterministically make sure limits apply and rest-calls see 429s.
2. ProduceRateLimitersTest.java, minor refactoring to improve readability.
=> KREST-9691 Add integration tests for the produce rate-limits for a single tenant.

kafka-rest/src/test/java/io/confluent/kafkarest/integration/ConsumerJsonTest.java
Pass-rate is 78% right now, increase timeout to improve pass-rate. One such failed instance -
`org.opentest4j.AssertionFailedError: test timed out waiting for consumers to finish. ==> expected:  but was:  	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55) 	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:40) 	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:210) 	at io.confluent.kafkarest.integration.ConsumerJsonTest.testConsumeWithMultipleParallelConsumers(ConsumerJsonTest.java:204) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at …
=> KREST-10170 Increase timeout to remove flakyness due to timeouts

kafka-rest/src/main/java/io/confluent/kafkarest/controllers/TopicManagerImpl.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/TopicsResource.java, kafka-rest/src/test/java/io/confluent/kafkarest/controllers/TopicManagerImplTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/TopicsResourceIntegrationTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/TopicsResourceTest.java
The operation to create a topic has a response schema which doesn't really match the underlying behaviour of Kafka particularly well. The response contains the `replication_factor` and `partitions_count` which are sometimes not possible to establish depending on authorization. Prior to this PR, in the case where the principal creating the topic has CREATE authority but not DESCRIBE_CONFIGS, the `POST /v3/clusters/{}/topics` request fails with `{"error_code":40301,"message":"Topic authorization failed."}` even when the topic is created successfully. The authorization failure is actually to access the replication factor, which comes back in the CreateTopicsResponse in the Kafka protocol, *provided* that the principal has DESCRIBE_CONFIGS authority. If principal does not have authority, the …
=> KREST-10318 Topic create without DESCRIBE_CONFIGS

kafka-rest/src/test/java/io/confluent/kafkarest/integration/ClusterTestHarness.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v2/SchemaProduceConsumeTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/ProduceActionNoSchemaIntegrationTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/ProduceActionRateLimitIntegrationTest.java
The v3 produce integration tests have been disabled because they prove unreliable in the CI system. Looking at the symptoms of the failing tests, the number of test cases and the complexity of the infrastructure are making it difficult to track down. This PR leaves the existing test present, but still disabled, and carves the non-schema tests and the rate-limit tests into their own integration tests. The batch tests run in about 1 second instead of nearer 60 seconds because the use of KafkaConsumer is much more efficient now.
=> KREST-4467 First part of reworking produce tests

kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/ListAllBrokersConfigsActionIntegrationTest.java
The value of the `num.network.threads` config in a test framework changed.
=> KREST-10360 Remove flaky broker config check

kafka-rest/src/test/java/io/confluent/kafkarest/integration/ConsumerJsonTest.java
As in the title, this test doesn't very consumer correctness and often flaky, temporary disabl this for now, there is a ticket to properly address this later.
=> Temporary disable flaky test

kafka-rest/src/main/java/io/confluent/kafkarest/response/JsonStreamMessageBodyReader.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/ProduceActionNoSchemaIntegrationTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/ProduceActionTest.java
This permits a Content-Type header that includes UTF-8 or ISO-8859-1 as a charset header parameters such as `Content-Type=application/json; charset=UTF-8`.
=> KREST-8294 Permit charset for v3 produce

kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/ProduceBatchActionIntegrationTest.java
Test failure from `ProduceBatchActionIntegrationTest.produceString` which didn't occur locally or on the branch build, but failed on master build. Temporarily disable the test to get the build green allowing investigation at leisure.
=> Disable integration test temporarily

kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/ProducerMetrics.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/ProducerMetricsTest.java
Simple fix, correctly use "rate" metric to record "produce-request-rate", instead of "avg".
=> KREST-10244 Fix produce-request-rate metric

checkstyle/import_control.xml, kafka-rest/pom.xml, kafka-rest/src/test/java/io/confluent/kafkarest/integration/ClusterTestHarness.java, kafka-rest/src/test/java/io/confluent/kafkarest/testing/KafkaBrokerFixture.java
This PR removes MockTime dependency to avoid upstream issue.
=> Remove the use of non-public API MockTime (in ce-kafka but not in AK)

kafka-rest/src/main/java/io/confluent/kafkarest/DefaultKafkaRestContext.java, kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestApplication.java, kafka-rest/src/main/java/io/confluent/kafkarest/converters/AvroConverter.java, kafka-rest/src/main/java/io/confluent/kafkarest/response/StreamingResponse.java
This is as part of reviewing our logging, I have checked across the repository and confirm that we don't log configuration.
=> Review logging, some code tidy up

kafka-rest/src/main/java/io/confluent/kafkarest/exceptions/KafkaRestExceptionMapper.java, kafka-rest/src/test/java/io/confluent/kafkarest/exceptions/KafkaRestExceptionMapperTest.java
As the title says. The reason is that without explicit MediaType, we might encounter the below error with OPTIONS request
```
org.glassfish.jersey.message.internal.MessageBodyProviderNotFoundException: MessageBodyWriter not found for media type=text/plain, type=class io.confluent.rest.entities.ErrorMessage, genericType=class io.confluent.rest.entities.ErrorMessage
```
=> Make sure that ErrorMessage is intepret as json type in response writer

kafka-rest/src/main/java/io/confluent/kafkarest/exceptions/KafkaRestExceptionMapper.java, kafka-rest/src/test/java/io/confluent/kafkarest/exceptions/KafkaRestExceptionMapperTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/AbstractConsumerTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/AuthorizationErrorTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/ConsumerBinaryTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/MetadataApiTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v2/BrokersResourceTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v2/RootResourceTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v2/TopicsResourceBinaryProduceTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v2/TopicsResourceTest.java
This reverts two commits that are related to explicit application/json media type on error response.
=> Krest 11086 revert commit that set explicit mediatype

kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestApplication.java, kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestConfig.java, kafka-rest/src/main/java/io/confluent/kafkarest/exceptions/ProduceRequestTooLargeException.java, kafka-rest/src/main/java/io/confluent/kafkarest/response/JsonStream.java, kafka-rest/src/main/java/io/confluent/kafkarest/response/JsonStreamMessageBodyReader.java, kafka-rest/src/main/java/io/confluent/kafkarest/response/StreamingResponse.java, kafka-rest/src/test/java/io/confluent/kafkarest/TestUtils.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/ProduceActionRequestSizeLimitIntegrationTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/response/JsonStreamTest.java
As part of OOM prevention, we should be able to stop the streaming/non-streaming produce connection if the produce request being parsed is too large. 
The current implementation allows such big requests coming through in JsonStream and it might be too late when it is successfully parsed, because the rate limit phase only comes after. For example, user can send 2GiB produce request to REST and when it is parsing the message, assuming Jackson needs the same space to parse, then it is already over 4GiB in memory at some point.
This PR introduces a wrapper for InputStream (`SizeLimitEntityStream`) that is being used in JsonStream so that we are able to keep track of how many bytes have been read when parsing a ProduceRequest, and when the number of bytes exceed a certain threshold …
=> Able to drop connection if produce request is larger than a threshold

kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestConfig.java, kafka-rest/src/test/java/io/confluent/kafkarest/KafkaRestConfigTest.java
This PR add two classes (inner class of `KafkaRestConfig`) that can be a direct replacement for  the two classes that are often used in creating configuration
- Properties
- Map<String, Object>
The two classes have overriden `toString` method that can hide sensitive configs. `toString` is the function that will get called in logging on the class.
This PR also uses the two new classes in all functions in `KafkaRestConfig` that return configurations so that they can be safely logged later. 
Reference JIRA: https://confluentinc.atlassian.net/browse/KREST-11068
=> Create custom Properties and Map configs classes with toString method that hides password properties

api/v3/openapi.yaml
Follow up the PR https://github.com/confluentinc/rest-utils/pull/411, this is to update API doc for produce records v3 API in kafka-rest
=> Add 413 response error for produce v3 api

.semaphore/project.yml, .semaphore/semaphore.yml, service.yml
Migration from Jenkins to Semaphore, for release branches, cherry-pick commits as instructed [here](https://confluentinc.atlassian.net/wiki/spaces/TOOLS/pages/3211693075/Jenkins+-+Semaphore+self+migration+guide#I-only-see-changes-for-master.-How-do-I-apply-to-release-branches%3F)
=> KREST-12277 semaphore migration to release branches

bin/kafka-rest-run-class
This small change to the startup class allows the jars for the Data Contract rules to be included in the classpath for the Kafka REST Proxy
The kafka-serde-tools subdir includes the client-side jars for the data quality rules and client-side field-level encryption.
=> DGS-9099 Enable Data Contract rules in Kafka REST Proxy

kafka-rest/pom.xml, pom.xml
Zookeeper dependency is updated in https://github.com/confluentinc/ce-kafka/pull/11994, which now requires extra dependency for running tests.
=> KREST-12630 Add missing dependency due to zookeeper upgrade

kafka-rest/pom.xml, pom.xml
Version 3.8.3 of zookeeper from [upstream](https://github.com/confluentinc/ce-kafka/pull/11994) makes tests hang, so use version 3.7.2 instead, this version also fixes the CVE-2023-44981
=> KREST-12630 Exclude logback from zookeeper dependency in tests

kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestConfig.java, kafka-rest/src/test/java/io/confluent/kafkarest/KafkaRestConfigTest.java
As title set, this provides more configurable to avro serialiser, for example, this `avro.use.logical.type.converters` config so that we are able to serialise logical type in avro message.
=> KREST-12797 Allow to set KafkaAvroSerializerConfig in KafkaRestConfig

Jenkinsfile
This PR removes the confluent-cloud-plugins and confluent-security-plugins repos as downstream repos in Jenkinsfile file (leaving them as downstream repos in service.yml/Semaphore). This change allows confluent-cloud-plugins and confluent-security-plugins to deprecate Jenkins without causing this repos downstream build to fail. A similar change to was made here: https://github.com/confluentinc/rest-utils/pull/443 to remove schema-registry from the Jenkinsfile.
=> Remove confluent-cloud-plugins and confluent-security-plugins as downstream in Jenkinsfile

kafka-rest/src/test/java/io/confluent/kafkarest/v2/KafkaConsumerManagerTest.java
See https://confluent.slack.com/archives/C06CFQNK2BF/p1704845102888579 for details.  This test continues to flake, and is disabled in master.  Matching that behaviour back in the 6.2.x branch
=> KREST-NNN disable flakey test

kafka-rest/src/main/java/io/confluent/kafkarest/v2/KafkaConsumerManager.java, kafka-rest/src/test/java/io/confluent/kafkarest/v2/KafkaConsumerManagerTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/v2/MockConsumer.java
This PR fixes the logic in `KafkaConsumerManager` class in the way it handles consumer backoff for readRecords
The approach that KafkaConsumerManager uses to execute backoff RunnableReadTask is:
- Each task has a fix backoff (in millis) and timeout (in millis)
- The [first run](https://github.com/confluentinc/kafka-rest/blob/6ad01a571a106f539cbfc8ed84ea900db3f367b0/kafka-rest/src/main/java/io/confluent/kafkarest/v2/KafkaConsumerManager.java#L336) is submitted in readRecords(...) function
- If the task is not done, then then task is [resubmitted into a DelayQueue](https://github.com/confluentinc/kafka-rest/blob/6ad01a571a106f539cbfc8ed84ea900db3f367b0/kafka-rest/src/main/java/io/confluent/kafkarest/v2/KafkaConsumerManager.java#L403) with [new calculated time to be …
=> KREST-2300 Deflake KafkaConsumerManagerTest.testBackoffMsControlsPollCalls test

kafka-rest/pom.xml, pom.xml
As title said. Add snappy-java test dependency to fix the error of ClassNotFoundException
=> KNET-13992 Fix java.lang.ClassNotFoundException: org.xerial.snappy.SnappyInputStream

kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestConfig.java, kafka-rest/src/test/java/io/confluent/kafkarest/KafkaRestConfigTest.java
Cherry-picking to ensure avro serializer is more configurable. 
This is ` avro.use.logical.type.converters` config so that we are able to serialize logical type in avro message.
=> Allow to set KafkaAvroSerializerConfig in KafkaRestConfig (#1229)

kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestConfig.java, kafka-rest/src/test/java/io/confluent/kafkarest/KafkaRestConfigTest.java
Ref: https://github.com/confluentinc/ce-kafka/pull/13010
For context, we don't want to log configuration values by default for transient clients in CCloud. This PRs introduces new constructors to `KafkaRestConfig` so that we can have the control over the logging behaviour. Note that, we don't use the `CONFIGS_LOGGING_ENABLED_PROP` config because it is internal, this config will be use in upstream project of kafka-rest.
Related PRs:
- [rest-utils](https://github.com/confluentinc/rest-utils/pull/464)
=> Add doLog parameter for KafkaRestConfig constructor

Jenkinsfile
As in [announcement](https://confluent.slack.com/archives/C06N5PM0W0G/p1709590990771839), we migrate this repo off Jenkins
=> Retire Jenkins CI

Jenkinsfile
As in [announcement](https://confluent.slack.com/archives/C06N5PM0W0G/p1709590990771839), we migrate this repo off Jenkins, this is for release branches
=> Retire Jenkins CI for release branches

.semaphore/semaphore.yml, service.yml
Update semaphore instance to a bigger machine type to avoid occasionally crashes in nightly builds.
=> Upscale Semaphore CI instance to avoid occasionally crash

kafka-rest/src/test/java/io/confluent/kafkarest/integration/AuthorizationErrorTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/testing/QuorumControllerFixture.java
ZkConnectProp is internal to server KafkaConfig, moving it to our public constant.
=> KNET-14854 Fix for ZkConnectProp that is moved in https://github.com/apache/kafka/pull/15075

kafka-rest/src/test/java/io/confluent/kafkarest/testing/KafkaBrokerFixture.java
The KRest build is failing due to various changes to KafkaConfig prop constant locations in AK. Currently the replication factor and interbrokerListenerName props have been moved, but since it seems plausible that a bunch of the props defined in `KafkaConfig` may change class locations, I went ahead and replaced references to KafkaConfig with fixed string constants.
=> CONFLUENT: Remove uses of KafkaConfig Prop constants

debian/Makefile
We are using different directory structure in SemaphoreCI in [packaging](https://github.com/confluentinc/packaging) repo and this leads to failure when building deb because of the check that is present in Makefile. This check is being removed as part of this PR.
=> CPBR-1311: Removing /tmp/confluent as the DSTDIR check in Makefile

kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestApplication.java, kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestConfig.java
Implement the change from https://github.com/FasterXML/jackson-core/issues/1001#issuecomment-1527216221
I'm using maxint for the value, as we do length checks of the stream elsewhere, and this seems safest to avoid a regression (see the code comment for more details)
=> KNET-15501 work around jackson databind string length limit

kafka-rest/pom.xml
org.apache.kafka.common.utils.SystemTime qualifier has been changed from public to default https://github.com/apache/kafka/pull/16266 . This is causing compilation failure for `io/confluent/kafkarest/SystemTime.java` . We will pin 7.8.0-100122-ccs as kafka-clients version so that we don't hit the compilation failure and unblock the release.
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.0:compile (default-compile) on project kafka-rest: Compilation failure
[ERROR] /home/semaphore/ce-kafka-images/.src/kafka-rest/kafka-rest/src/main/java/io/confluent/kafkarest/SystemTime.java:[21,62] org.apache.kafka.common.utils.SystemTime is not public in org.apache.kafka.common.utils; cannot be accessed from outside package
```
discussion : …
=> Pin kafka version to 7.8.0-100122-ccs to fix SystemTime cannot be accessed from outside package

kafka-rest/pom.xml, kafka-rest/src/main/java/io/confluent/kafkarest/SystemTime.java
SystemTime is using a class that is now package private, so using delegate to fix that.
And using kafka nano version so that it will load with the latest ak build that fix _ issue.
=> Fix SystemTime and revert pin ak version

kafka-rest/src/main/java/io/confluent/kafkarest/DefaultKafkaRestContext.java
This PR provides the implementation for the `getConsumer` method in the DefaultKafkaRestContext class. This follows the addition of the default `getConsumer` interface method in a previous PR https://github.com/confluentinc/kafka-rest/pull/1289
=> Implement getConsumer in DefaultKafkaRestContext

kafka-rest/src/test/java/io/confluent/kafkarest/integration/ClusterTestHarness.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v2/TopicsResourceAvroProduceTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v2/TopicsResourceBinaryProduceTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/testing/QuorumControllerFixture.java
https://github.com/apache/kafka/pull/16979/files remove the RecordMetadata constructor kafka rest was using
Old method signature was
TopicPartition topicPartition, long baseOffset, long batchIndex, long timestamp,
Long checksum, int serializedKeySize, int serializedValueSize
new is
TopicPartition topicPartition, long baseOffset, int batchIndex, long timestamp,
int serializedKeySize, int serializedValueSize
So I've turned batch index from a long to an int, and removed the checksum.
AND
https://github.com/apache/kafka/pull/16866 updated the method signature on QuorumTestHarness.kraftContorllerConfigs, so I've updated our overriding method to match
=>  Fix build breaks due to upstream changes

kafka-rest/pom.xml, pom.xml
Protobuf-java is bumped from 3.25.4 to 3.25.5 by bumping up all the dependencies of kafka-rest indirectly.
This has been tested by scanning the bom files produced by Maven using trivy, and make sure no vulnerabilities are found.
=> CONMON-9817: protobuf-java

kafka-rest/src/test/java/io/confluent/kafkarest/integration/AuthorizationErrorTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/SchemaRegistrySaslInheritTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/AclsResourceIntegrationTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/ProduceActionRateLimitIntegrationTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/ProduceActionRequestSizeLimitIntegrationTest.java
- `AclAuthorizer` is deprecated. Removing ZK tests using `AclAuthorizer`
- `AuthorizationErrorTest` is ZK specific. Disabling the test temporarily. `StandardAuthorizer` to be used instead to support Kraft case.
=> Remove/Disable ZK specific tests in Kafka Rest

kafka-rest/src/test/java/io/confluent/kafkarest/integration/ClusterTestHarness.java
This PR provides:
- a new constructor `ClusterTestHarness(int numBrokers, boolean withSchemaRegistry, boolean startRest)` with the option to startRest
- startRest(String bootstrapServers) to start Kafka Rest manually
- and utility function getBootstrapServers to get broker bootstrap server
The change is backward compatible.
=> Allow to start kafka rest separately so that the integration test can be more customisable

kafka-rest/src/test/java/io/confluent/kafkarest/integration/ClusterTestHarness.java
From branch 7.6.x, we already have property name `manageRest`, so this change is to make it consistent for all branches, also fix the missing check in tearDown.
=> Change to manageRest to make the name consistent for all release branch

kafka-rest/src/test/java/io/confluent/kafkarest/integration/ClusterTestHarness.java
`stopRest` needs to be `protected` visibility so that it can be used by subclasses.
=> Fix visibility for stopRest function

api/v3/openapi.yaml
`consumers` as field name is used in `ConsumerGroupData.java`, further [required](https://github.com/confluentinc/kafka-rest/pull/1324/files#diff-15612e27820603f2efe1f27c21963e53492df05773f3c9b4489fc575582ced9cR2135) also lists field name as `consumers`
=> Correct field name in ConsumerGroupData, consumer -> consumers to mach code/examples

checkstyle/import_control.xml, kafka-rest/src/main/java/io/confluent/kafkarest/requestlog/GlobalDosFilterListener.java, kafka-rest/src/main/java/io/confluent/kafkarest/requestlog/PerConnectionDosFilterListener.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/AuthorizationErrorTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/AvroProducerTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/ClusterTestHarness.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/AclsResourceIntegrationTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/ClustersResourceIntegrationTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/testing/KafkaBrokerFixture.java
Remove all zk dependencies, make sure tests are running with KRaft.
This PR replaces the default jetty DOSFilter with our fork.
=> Remove zk and replace jetty DOSFilter with Confluent fork

kafka-rest/src/test/java/io/confluent/kafkarest/controllers/SchemaManagerImplTest.java
Tests that use `EasyMock` can't mock `private static final` classes if using the latest version of `EasyMock`. Temporarily disable tests to unblock build.
=> Temporarily disable unit tests in `SchemaManagerImplTest`

kafka-rest/src/main/java/io/confluent/kafkarest/controllers/ConsumerGroupManagerImpl.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/ConsumerGroup.java, kafka-rest/src/test/java/io/confluent/kafkarest/controllers/ConsumerGroupManagerImplTest.java
Revert changes made by 0b6b7b6ffdf17cf80a3a2ce0fcebd3a7df532309 and use `.state()` where needed.
=> Use backward compatible method to fix downstream build

kafka-rest/src/test/java/io/confluent/kafkarest/integration/AuthorizationErrorTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/ClusterTestHarness.java, kafka-rest/src/test/java/io/confluent/kafkarest/testing/KafkaBrokerFixture.java
Change in upstream https://github.com/confluentinc/kafka/commit/d874aa42f3d54f1474f2e617c792e48ed01f6a77 has removed a param (zkConnect) from `TestUtils.createBrokerConfig` function, this is to fixes it to make kafka-rest build pass.
=> Fix build due to upstream change

kafka-rest/src/test/java/io/confluent/kafkarest/integration/ClusterTestHarness.java
Change visibility of testInfo and quorumTestHarness to protected so they can be used by subclasses.
This will help with customising subclasses for ce-kafka-rest to fix issue regarding deprecating zk.
=> Change visibility of testInfo and quorumTestHarness to protected so they can be used by subclasses

kafka-rest/pom.xml
For context, kafka core [bring log4j2 dependencies](https://github.com/confluentinc/kafka/commit/b37b89c6686f5270b37d39cf3144bccb4f5bceb2#diff-a74b4a65ab1f4aed61344787bb9654ba7e835154730653848c88ca11f9965dc0R243) (particularly log4j-1.2-api) that is clashing with reload4j.
This fixes the issue by excluding log4j2 deps from kafka-rest
=> Exclude log4j2 deps from kafka

kafka-rest/pom.xml
kafka-rest doesn't use kafka_2.13 other than testing so we remove the dep, also excluding log4j2 compatibility jars to make sure that we don't clash on logging library
=> Remove kafka_2.13 dependency, only for testing and exclude log4j2 compatibility jar

kafka-rest/pom.xml
Hotfix [PR](https://github.com/confluentinc/kafka-rest/pull/1340) cherry-picked for master
=> Remove kafka_2.13 dep and exclude log4j2 compatibility jar

kafka-rest/src/main/java/io/confluent/kafkarest/requestlog/GlobalDosFilterListener.java, kafka-rest/src/main/java/io/confluent/kafkarest/requestlog/PerConnectionDosFilterListener.java, pom.xml
Use `org.eclipse.jetty.servlets.DoSFilter` in release branch for green image build.
=> Revert to old DosFilter

kafka-rest/src/main/java/io/confluent/kafkarest/requestlog/GlobalDosFilterListener.java, kafka-rest/src/main/java/io/confluent/kafkarest/requestlog/PerConnectionDosFilterListener.java
rest-utils is updating the 7.8.x branch to include changes to DosFilter - https://github.com/confluentinc/rest-utils/pull/535
this PR resolves build errors that would've occurred
=> [7.8.x] Use Confluent package for DosFilter

checkstyle/import_control.xml, checkstyle/suppressions.xml, kafka-rest/pom.xml, kafka-rest/src/main/java/io/confluent/kafkarest/entities/ConsumerGroup.java, kafka-rest/src/test/java/io/confluent/kafkarest/entities/ConsumerGroupTest.java
This implement `hashCode` for ConsumerGroup.State since we need to override both equals and hashCode to ensure consistency of a class.
=> [KNET-17449] Implement hashCode for ConsumerGroup.State to satisfy equals contract

api/v3/openapi.yaml, kafka-rest/src/main/java/io/confluent/kafkarest/entities/ConsumerGroup.java, kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/ConsumerGroupData.java, kafka-rest/src/test/java/io/confluent/kafkarest/controllers/ConsumerGroupLagSummaryManagerImplTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/controllers/ConsumerGroupManagerImplTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/controllers/ConsumerLagManagerImplTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/controllers/ConsumerManagerImplTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/ClusterTestHarness.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/ConsumerGroupsResourceIntegrationTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/ConsumerGroupsResourceTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/ConsumersResourceTest.java
This patch adds two protocol related fields to `ListConsumerGroups` api.
- Group protocol (CLASSIC, CONSUMER, SHARE, UNKNOWN)
- New field to indicate whether a group with the consumer protocol does/does not have all its assigned consumers on the new protocol. The boolean is set to be false for groups using protocols other than CONSUMER.
Beside, it also updates the `state` field to have the new states of the new protocol ASSIGNING and RECONCILING.
=> KCOORD-966: Add protocol related fields to list consumer groups api

kafka-rest/src/main/java/io/confluent/kafkarest/Errors.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/AclsResource.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/AlterBrokerConfigBatchAction.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/AlterClusterConfigBatchAction.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/AlterTopicConfigBatchAction.java, kafka-rest/src/main/java/io/confluent/kafkarest/resources/v3/CreateAclBatchAction.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/AlterBrokerConfigBatchActionTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/AlterClusterConfigBatchActionTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/AlterTopicConfigBatchActionTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/resources/v3/CreateAclBatchActionTest.java
Even though we annotate the payload with `@Valid` annotation, we might still receive null payload, this will cause the endpoint to return 500 due to NPE of the payload, this PR fixes the issue by checking the nullability of the payload and return 422 if that is the case.
The fix in this PR is for v3 resources.
=> Handle null payload in POST requests

kafka-rest/src/main/java/io/confluent/kafkarest/KafkaRestConfig.java, kafka-rest/src/main/java/io/confluent/kafkarest/config/ConfigModule.java, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/ControllersModule.java, kafka-rest/src/main/java/io/confluent/kafkarest/controllers/SchemaRecordSerializerImpl.java, kafka-rest/src/test/java/io/confluent/kafkarest/controllers/ControllersModuleTest.java
A follow up to this PR - https://github.com/confluentinc/kafka-rest/pull/1360, refactoring the config name and documentation for clarity.
=> refactor: changing the config introduced in the commit d65a0b3

kafka-rest/src/test/java/io/confluent/kafkarest/integration/CustomLogIntegrationTest.java
We saw a test failure for `test_whenGlobalProduceBytesRateLimitTriggered_ThenRequestLogHasRelevantInfo` in which we saw the 400 error code that we weren't expected. However, it seems the test is only supposed to send 100 requests (logs 0 to 99). Log 100 and 101 are unknown, and could be caused by a separate thing since they happen much later than the requests our test sends. We can fix some of this flakiness by making sure we just check the request log for the exact number of requests we know we send.
Example logs for failure:
```
...
[2025-04-07 18:43:55,840] INFO Log #98:200 429003 Codes=429:1 (io.confluent.kafkarest.integration.CustomLogIntegrationTest:486)
[2025-04-07 18:43:55,840] INFO Log #99:200 429003 Codes=429:1 (io.confluent.kafkarest.integration.CustomLogIntegrationTest:486) …
```
=> KNET-18123: Do not overcheck the custom request log

bin/kafka-rest-run-class, kafka-rest/src/main/resources/log4j.properties, kafka-rest/src/main/resources/log4j2.yaml
Convert properties file to yaml and update references.
Follow up of #1368
=> KNET-18079: Convert log4j2 properties file to yaml

kafka-rest/src/test/java/io/confluent/kafkarest/integration/AuthorizationErrorTest.java, kafka-rest/src/test/java/io/confluent/kafkarest/integration/v3/ClustersResourceIntegrationTest.java
This PR fixed several zk only tests to kraft.
=> KNET-17072: Remove zk support for kafka-rest integration tests

kafka-rest/pom.xml, pom.xml
Version is bumped by bot via [fa71840](https://github.com/confluentinc/kafka-rest/commit/fa7184019572b6a97b681b23b6372cc28a105820). We need to merge this commit to `8.0.x` to avoid merge conflicts
=> cherry pick fa71840

.semaphore/semaphore.yml
This PR updates the Ubuntu version from 20 to 24 in all Semaphore configuration files.
=> Update Ubuntu version from 20 to 24

api/v3/openapi.yaml
One of the sections in the CP docs is incorrectly pointing to the cloud. This PR fixes the issue.
Doc link: https://confluentinc.atlassian.net/browse/DOCS-25908
Issue doc link: https://docs.confluent.io/platform/current/kafka-rest/api.html#section/Versioning/API-Lifecycle-Policy:~:text=Get%20Consumer%20Group%20Lag%20Summary
=> [MINOR]DOCS-25908:remove incorrect doc link that is directing to cloud docs
